md Sparta
copy 1941.zip .\Sparta\
copy 1942.zip .\Sparta\
copy 1943.zip .\Sparta\
copy 1943mii.zip .\Sparta\
copy 1944.zip .\Sparta\
copy 1945kiii.zip .\Sparta\
copy 19xx.zip .\Sparta\
copy 2020bb.zip .\Sparta\
copy 3countb.zip .\Sparta\
copy 64street.zip .\Sparta\
copy 720.zip .\Sparta\
copy 88games.zip .\Sparta\
copy 8ballact.zip .\Sparta\
copy acrobatm.zip .\Sparta\
copy aerofgt.zip .\Sparta\
copy afighter.zip .\Sparta\
copy agallet.zip .\Sparta\
copy airwolf.zip .\Sparta\
copy alcon.zip .\Sparta\
copy alibaba.zip .\Sparta\
copy aliens.zip .\Sparta\
copy aliensyn.zip .\Sparta\
copy aligator.zip .\Sparta\
copy alpham2.zip .\Sparta\
copy altbeast.zip .\Sparta\
copy amazon.zip .\Sparta\
copy amidar.zip .\Sparta\
copy androdun.zip .\Sparta\
copy anteater.zip .\Sparta\
copy apb.zip .\Sparta\
copy arabfgt.zip .\Sparta\
copy arabian.zip .\Sparta\
copy arabianm.zip .\Sparta\
copy arbalest.zip .\Sparta\
copy argus.zip .\Sparta\
copy arkanoid.zip .\Sparta\
copy arkarea.zip .\Sparta\
copy arknoid2.zip .\Sparta\
copy arkretrn.zip .\Sparta\
copy armedf.zip .\Sparta\
copy armora.zip .\Sparta\
copy assault.zip .\Sparta\
copy astdelux.zip .\Sparta\
copy asterix.zip .\Sparta\
copy asteroid.zip .\Sparta\
copy astinvad.zip .\Sparta\
copy astorm2p.zip .\Sparta\
copy astyanax.zip .\Sparta\
copy avengers.zip .\Sparta\
copy avsp.zip .\Sparta\
copy avspirit.zip .\Sparta\
copy baddudes.zip .\Sparta\
copy bagman.zip .\Sparta\
copy baraduke.zip .\Sparta\
copy baryon.zip .\Sparta\
copy batman.zip .\Sparta\
copy batmanfr.zip .\Sparta\
copy batrider.zip .\Sparta\
copy battlnts.zip .\Sparta\
copy battroad.zip .\Sparta\
copy bayroute.zip .\Sparta\
copy berzerk.zip .\Sparta\
copy bigkarnk.zip .\Sparta\
copy bionicc.zip .\Sparta\
copy blktiger.zip .\Sparta\
copy blueprnt.zip .\Sparta\
copy bmaster.zip .\Sparta\
copy bombbee.zip .\Sparta\
copy bombjack.zip .\Sparta\
copy bombrman.zip .\Sparta\
copy boothill.zip .\Sparta\
copy bosco.zip .\Sparta\
copy bouldash.zip .\Sparta\
copy brkthru.zip .\Sparta\
copy brubber.zip .\Sparta\
copy btime.zip .\Sparta\
copy btoads.zip .\Sparta\
copy bublbobl.zip .\Sparta\
copy buckrog.zip .\Sparta\
copy bucky.zip .\Sparta\
copy bwidow.zip .\Sparta\
copy bzone.zip .\Sparta\
copy cabal.zip .\Sparta\
copy cadash.zip .\Sparta\
copy calibr50.zip .\Sparta\
copy cameltry.zip .\Sparta\
copy capbowl.zip .\Sparta\
copy captaven.zip .\Sparta\
copy captcomm.zip .\Sparta\
copy carnival.zip .\Sparta\
copy cavelon.zip .\Sparta\
copy centiped.zip .\Sparta\
copy cerberus.zip .\Sparta\
copy ckong.zip .\Sparta\
copy cloak.zip .\Sparta\
copy cobracom.zip .\Sparta\
copy colmns97.zip .\Sparta\
copy colony7.zip .\Sparta\
copy columns.zip .\Sparta\
copy columns2.zip .\Sparta\
copy commando.zip .\Sparta\
copy contra.zip .\Sparta\
copy copsnrob.zip .\Sparta\
copy crimfght.zip .\Sparta\
copy cyvern.zip .\Sparta\
copy darius.zip .\Sparta\
copy darkmist.zip .\Sparta\
copy darkseal.zip .\Sparta\
copy darktowr.zip .\Sparta\
copy dbreed.zip .\Sparta\
copy ddonpach.zip .\Sparta\
copy ddragon.zip .\Sparta\
copy ddragon2.zip .\Sparta\
copy ddragon3.zip .\Sparta\
copy ddsom.zip .\Sparta\
copy ddtod.zip .\Sparta\
copy defender.zip .\Sparta\
copy desertwr.zip .\Sparta\
copy digdug.zip .\Sparta\
copy disco.zip .\Sparta\
copy dkong.zip .\Sparta\
copy dkong3.zip .\Sparta\
copy dkongjr.zip .\Sparta\
copy docastle.zip .\Sparta\
copy donpachi.zip .\Sparta\
copy dorunrun.zip .\Sparta\
copy dotron.zip .\Sparta\
copy drtoppel.zip .\Sparta\
copy dsaber.zip .\Sparta\
copy dspirit.zip .\Sparta\
copy dungeonm.zip .\Sparta\
copy elevator.zip .\Sparta\
copy empcity.zip .\Sparta\
copy esb.zip .\Sparta\
copy espgal.zip .\Sparta\
copy esprade.zip .\Sparta\
copy fantland.zip .\Sparta\
copy ffight.zip .\Sparta\
copy flashgal.zip .\Sparta\
copy foodf.zip .\Sparta\
copy frenzy.zip .\Sparta\
copy frogger.zip .\Sparta\
copy galaga.zip .\Sparta\
copy galaga88.zip .\Sparta\
copy galagamf.zip .\Sparta\
copy galaxian.zip .\Sparta\
copy gaplus.zip .\Sparta\
copy gaunt22p.zip .\Sparta\
copy gaunt2p.zip .\Sparta\
copy gbusters.zip .\Sparta\
copy ghouls.zip .\Sparta\
copy gigawing.zip .\Sparta\
copy gijoe.zip .\Sparta\
copy gng.zip .\Sparta\
copy goldnaxe.zip .\Sparta\
copy goonies.zip .\Sparta\
copy gorf.zip .\Sparta\
copy gradius3.zip .\Sparta\
copy gravitar.zip .\Sparta\
copy gulfstrm.zip .\Sparta\
copy gulfwar2.zip .\Sparta\
copy gunsmoke.zip .\Sparta\
copy gyruss.zip .\Sparta\
copy halleys.zip .\Sparta\
copy hangon.zip .\Sparta\
copy hbarrel.zip .\Sparta\
copy hcastle.zip .\Sparta\
copy headon.zip .\Sparta\
copy ikari.zip .\Sparta\
copy ikari3.zip .\Sparta\
copy indytemp.zip .\Sparta\
copy invaddlx.zip .\Sparta\
copy invaders.zip .\Sparta\
copy jackal.zip .\Sparta\
copy jedi.zip .\Sparta\
copy joust.zip .\Sparta\
copy joust2.zip .\Sparta\
copy jrpacman.zip .\Sparta\
copy junglek.zip .\Sparta\
copy karnov.zip .\Sparta\
copy klax.zip .\Sparta\
copy knights.zip .\Sparta\
copy kod.zip .\Sparta\
copy krull.zip .\Sparta\
copy kungfum.zip .\Sparta\
copy ladybug.zip .\Sparta\
copy liberate.zip .\Sparta\
copy liberatr.zip .\Sparta\
copy maglord.zip .\Sparta\
copy mappy.zip .\Sparta\
copy marble.zip .\Sparta\
copy mario.zip .\Sparta\
copy megaman.zip .\Sparta\
copy megaman2.zip .\Sparta\
copy mercs.zip .\Sparta\
copy mhavoc.zip .\Sparta\
copy milliped.zip .\Sparta\
copy missile.zip .\Sparta\
copy mk.zip .\Sparta\
copy mk2.zip .\Sparta\
copy mk3.zip .\Sparta\
copy moonwalk.zip .\Sparta\
copy mpatrol.zip .\Sparta\
copy mrdo.zip .\Sparta\
copy msh.zip .\Sparta\
copy mshvsf.zip .\Sparta\
copy mslug.zip .\Sparta\
copy mslug2.zip .\Sparta\
copy mslug3.zip .\Sparta\
copy mslug4.zip .\Sparta\
copy mslug5.zip .\Sparta\
copy mslugx.zip .\Sparta\
copy mspacman.zip .\Sparta\
copy mspacmnf.zip .\Sparta\
copy msword.zip .\Sparta\
copy mvsc.zip .\Sparta\
copy narc.zip .\Sparta\
copy nbbatman.zip .\Sparta\
copy neogeo.zip .\Sparta\
copy opwolf.zip .\Sparta\
copy opwolf3.zip .\Sparta\
copy othunder.zip .\Sparta\
copy pacland.zip .\Sparta\
copy pacman.zip .\Sparta\
copy pacmanf.zip .\Sparta\
copy pacmania.zip .\Sparta\
copy pacnpal.zip .\Sparta\
copy pacplus.zip .\Sparta\
copy paperboy.zip .\Sparta\
copy pbobble.zip .\Sparta\
copy pbobble2.zip .\Sparta\
copy pbobble3.zip .\Sparta\
copy pbobble4.zip .\Sparta\
copy pengo.zip .\Sparta\
copy phoenix.zip .\Sparta\
copy pinbo.zip .\Sparta\
copy pingpong.zip .\Sparta\
copy pitfall2.zip .\Sparta\
copy polepos.zip .\Sparta\
copy polepos2.zip .\Sparta\
copy popeye.zip .\Sparta\
copy pow.zip .\Sparta\
copy primrage.zip .\Sparta\
copy punisher.zip .\Sparta\
copy qbert.zip .\Sparta\
copy qix.zip .\Sparta\
copy quantum.zip .\Sparta\
copy raiden.zip .\Sparta\
copy raiden2.zip .\Sparta\
copy rallyx.zip .\Sparta\
copy rambo3.zip .\Sparta\
copy rampage.zip .\Sparta\
copy rastsaga.zip .\Sparta\
copy renegade.zip .\Sparta\
copy roadblst.zip .\Sparta\
copy roadf.zip .\Sparta\
copy robocop.zip .\Sparta\
copy robocop2.zip .\Sparta\
copy robotron.zip .\Sparta\
copy rtype.zip .\Sparta\
copy rtype2.zip .\Sparta\
copy rushatck.zip .\Sparta\
copy s1945.zip .\Sparta\
copy s1945ii.zip .\Sparta\
copy s1945iii.zip .\Sparta\
copy s1945p.zip .\Sparta\
copy salamand.zip .\Sparta\
copy samsho.zip .\Sparta\
copy samsho2.zip .\Sparta\
copy samsho3.zip .\Sparta\
copy samsho4.zip .\Sparta\
copy sbrkout.zip .\Sparta\
copy scontra.zip .\Sparta\
copy sectionz.zip .\Sparta\
copy sf1.zip .\Sparta\
copy sf2.zip .\Sparta\
copy sf2ce.zip .\Sparta\
copy sfa.zip .\Sparta\
copy sfa2.zip .\Sparta\
copy sfa3.zip .\Sparta\
copy sfx.zip .\Sparta\
copy shangon.zip .\Sparta\
copy sharrier.zip .\Sparta\
copy shinobi.zip .\Sparta\
copy shollow.zip .\Sparta\
copy sidepckt.zip .\Sparta\
copy silkroad.zip .\Sparta\
copy simpsn2p.zip .\Sparta\
copy sinistar.zip .\Sparta\
copy smashtv.zip .\Sparta\
copy snowbro2.zip .\Sparta\
copy snowbros.zip .\Sparta\
copy solarfox.zip .\Sparta\
copy solarq.zip .\Sparta\
copy solomon.zip .\Sparta\
copy sonicwi2.zip .\Sparta\
copy sonicwi3.zip .\Sparta\
copy spacduel.zip .\Sparta\
copy spidey.zip .\Sparta\
copy spnchout.zip .\Sparta\
copy spyhunt.zip .\Sparta\
copy ssf2.zip .\Sparta\
copy ssriders.zip .\Sparta\
copy starfigh.zip .\Sparta\
copy stargate.zip .\Sparta\
copy startrek.zip .\Sparta\
copy starwars.zip .\Sparta\
copy strider.zip .\Sparta\
copy strider2.zip .\Sparta\
copy supbtime.zip .\Sparta\
copy superman.zip .\Sparta\
copy superpac.zip .\Sparta\
copy superqix.zip .\Sparta\
copy superspy.zip .\Sparta\
copy szaxxon.zip .\Sparta\
copy tacscan.zip .\Sparta\
copy tapper.zip .\Sparta\
copy tempest.zip .\Sparta\
copy temptube.zip .\Sparta\
copy tetris.zip .\Sparta\
copy tigerh.zip .\Sparta\
copy tigeroad.zip .\Sparta\
copy timeplt.zip .\Sparta\
copy tmht2p.zip .\Sparta\
copy tmnt22p.zip .\Sparta\
copy tmnt2po.zip .\Sparta\
copy tnk3.zip .\Sparta\
copy todruaga.zip .\Sparta\
copy tp84.zip .\Sparta\
copy trackfld.zip .\Sparta\
copy trojan.zip .\Sparta\
copy tron.zip .\Sparta\
copy vampj.zip .\Sparta\
copy vangrd2.zip .\Sparta\
copy vanguard.zip .\Sparta\
copy victroad.zip .\Sparta\
copy vsav.zip .\Sparta\
copy vsav2.zip .\Sparta\
copy willow.zip .\Sparta\
copy wow.zip .\Sparta\
copy xenophob.zip .\Sparta\
copy xevious.zip .\Sparta\
copy xmcota.zip .\Sparta\
copy xmen2p.zip .\Sparta\
copy xmvsf.zip .\Sparta\
copy yard.zip .\Sparta\
copy zaxxon.zip .\Sparta\
copy zookeep.zip .\Sparta\