;=============================================
; Create folder and move Mature, Quiz, Rhythm,
; and Tabletop games into it. This should
; include most casino/slots games as well.
;=============================================

md MQRT

move blckgalb.zip .\MQRT\
move peekaboo.zip .\MQRT\
move plgirls.zip .\MQRT\
move lottofun.zip .\MQRT\
move sxyreact.zip .\MQRT\
move blandia.zip .\MQRT\
move blandiap.zip .\MQRT\
move stoffy.zip .\MQRT\
move maddonna.zip .\MQRT\
move maddonnb.zip .\MQRT\
move usg185.zip .\MQRT\
move usg252.zip .\MQRT\
move usg32.zip .\MQRT\
move 3in1semi.zip .\MQRT\
move galspnbl.zip .\MQRT\
move hotpinbl.zip .\MQRT\
move spbactn.zip .\MQRT\
move spbactnj.zip .\MQRT\
move pipibibi.zip .\MQRT\
move pipibibs.zip .\MQRT\
move whoopee.zip .\MQRT\
move bballs.zip .\MQRT\
move bigtwin.zip .\MQRT\
move grndtour.zip .\MQRT\
move gumbo.zip .\MQRT\
move gundeala.zip .\MQRT\
move gundealr.zip .\MQRT\
move gundealt.zip .\MQRT\
move gundl94.zip .\MQRT\
move hexa.zip .\MQRT\
move lvgirl94.zip .\MQRT\
move magix.zip .\MQRT\
move primella.zip .\MQRT\
move sadari.zip .\MQRT\
move zerozone.zip .\MQRT\
move 3kokushi.zip .\MQRT\
move lastfero.zip .\MQRT\
move maya.zip .\MQRT\
move niyanpai.zip .\MQRT\
move pairs.zip .\MQRT\
move pairsa.zip .\MQRT\
move pairsten.zip .\MQRT\
move puzznic.zip .\MQRT\
move rongrong.zip .\MQRT\
move sichuan2.zip .\MQRT\
move sshanghb.zip .\MQRT\
move fantasia.zip .\MQRT\
move fantsia2.zip .\MQRT\
move fantsy95.zip .\MQRT\
move galpani2.zip .\MQRT\
move galpani4.zip .\MQRT\
move galpanib.zip .\MQRT\
move galpanic.zip .\MQRT\
move galpanis.zip .\MQRT\
move galpans2.zip .\MQRT\
move ladykill.zip .\MQRT\
move missw96.zip .\MQRT\
move moegonta.zip .\MQRT\
move newfant.zip .\MQRT\
move paradise.zip .\MQRT\
move perestro.zip .\MQRT\
move splash.zip .\MQRT\
move bubl2000.zip .\MQRT\
move cannball.zip .\MQRT\
move funybubl.zip .\MQRT\
move quizchql.zip .\MQRT\
move bigbucks.zip .\MQRT\
move fax.zip .\MQRT\
move nametune.zip .\MQRT\
move qad.zip .\MQRT\
move statriv2.zip .\MQRT\
move strvmstr.zip .\MQRT\
move triviabb.zip .\MQRT\
move triviag1.zip .\MQRT\
move triviag2.zip .\MQRT\
move triviasp.zip .\MQRT\
move triviayp.zip .\MQRT\
move trivquiz.zip .\MQRT\
move wfortuna.zip .\MQRT\
move wfortune.zip .\MQRT\
move supertr2.zip .\MQRT\
move findout.zip .\MQRT\
move atehate.zip .\MQRT\
move bkrtmaq.zip .\MQRT\
move cworld2j.zip .\MQRT\
move cworld.zip .\MQRT\
move gakupara.zip .\MQRT\
move gekiretu.zip .\MQRT\
move hatena.zip .\MQRT\
move hayaosi1.zip .\MQRT\
move hotdebut.zip .\MQRT\
move inufuku.zip .\MQRT\
move keithlcy.zip .\MQRT\
move kirameki.zip .\MQRT\
move marukodq.zip .\MQRT\
move myangel2.zip .\MQRT\
move myangel3.zip .\MQRT\
move myangel.zip .\MQRT\
move nettoqc.zip .\MQRT\
move nouryoku.zip .\MQRT\
move qadj.zip .\MQRT\
move qcrayon2.zip .\MQRT\
move qcrayon.zip .\MQRT\
move qgakumon.zip .\MQRT\
move qgh.zip .\MQRT\
move qjinsei.zip .\MQRT\
move qndream.zip .\MQRT\
move qrouka.zip .\MQRT\
move qsangoku.zip .\MQRT\
move qtheater.zip .\MQRT\
move qtono1.zip .\MQRT\
move qtono2.zip .\MQRT\
move qtorimon.zip .\MQRT\
move quizchq.zip .\MQRT\
move quizdai2.zip .\MQRT\
move quizdais.zip .\MQRT\
move quizdna.zip .\MQRT\
move quizf1.zip .\MQRT\
move quizhq.zip .\MQRT\
move quizhuhu.zip .\MQRT\
move quizkof.zip .\MQRT\
move quizmeku.zip .\MQRT\
move quizmoon.zip .\MQRT\
move quizpani.zip .\MQRT\
move quiztou.zip .\MQRT\
move quiztvqq.zip .\MQRT\
move qzchikyu.zip .\MQRT\
move qzkklgy2.zip .\MQRT\
move qzkklogy.zip .\MQRT\
move qzquest.zip .\MQRT\
move qzshowby.zip .\MQRT\
move ryorioh.zip .\MQRT\
move yesnoj.zip .\MQRT\
move yuyugogo.zip .\MQRT\
move hyhoo2.zip .\MQRT\
move hyhoo.zip .\MQRT\
move quiz18k.zip .\MQRT\
move bm1stmix.zip .\MQRT\
move bm2ndmix.zip .\MQRT\
move bm2ndmxa.zip .\MQRT\
move bm4thmix.zip .\MQRT\
move bmcompmx.zip .\MQRT\
move bmcorerm.zip .\MQRT\
move bmdct.zip .\MQRT\
move hmcompm2.zip .\MQRT\
move hmcompmx.zip .\MQRT\
move rockn2.zip .\MQRT\
move rockn3.zip .\MQRT\
move rockn4.zip .\MQRT\
move rockn.zip .\MQRT\
move rockna.zip .\MQRT\
move sexyparo.zip .\MQRT\
move plgirls2.zip .\MQRT\
move galhustl.zip .\MQRT\
move pcktgal2.zip .\MQRT\
move pcktgal.zip .\MQRT\
move pcktgalb.zip .\MQRT\
move pktgaldj.zip .\MQRT\
move pktgaldx.zip .\MQRT\
move realbrk.zip .\MQRT\
move 4enraya.zip .\MQRT\
move ataxx.zip .\MQRT\
move ataxxa.zip .\MQRT\
move ataxxj.zip .\MQRT\
move gomoku.zip .\MQRT\
move mosyougi.zip .\MQRT\
move othldrby.zip .\MQRT\
move ddenlovr.zip .\MQRT\
move gfire2.zip .\MQRT\
move acitya.zip .\MQRT\
move bwcasino.zip .\MQRT\
move cluckypo.zip .\MQRT\
move hitme.zip .\MQRT\
move mblkjack.zip .\MQRT\
move showdown.zip .\MQRT\
move speedatk.zip .\MQRT\
move sucasino.zip .\MQRT\
move truco.zip .\MQRT\
move pkladiel.zip .\MQRT\
move pkladies.zip .\MQRT\
move untoucha.zip .\MQRT\
move hanaawas.zip .\MQRT\
move hanaroku.zip .\MQRT\
move gionbana.zip .\MQRT\
move hanamai.zip .\MQRT\
move hanaoji.zip .\MQRT\
move hnayayoi.zip .\MQRT\
move hnfubuki.zip .\MQRT\
move hnkochou.zip .\MQRT\
move hnoridur.zip .\MQRT\
move koikois2.zip .\MQRT\
move maiko.zip .\MQRT\
move kiwame.zip .\MQRT\
move mahmajn2.zip .\MQRT\
move mahmajn.zip .\MQRT\
move minasan.zip .\MQRT\
move mjnquesb.zip .\MQRT\
move royalmah.zip .\MQRT\
move sengokmj.zip .\MQRT\
move ttmahjng.zip .\MQRT\
move vsmahjng.zip .\MQRT\
move 47pie2.zip .\MQRT\
move 47pie2o.zip .\MQRT\
move 7jigen.zip .\MQRT\
move 7toitsu.zip .\MQRT\
move akiss.zip .\MQRT\
move apparel.zip .\MQRT\
move av2mj1bb.zip .\MQRT\
move av2mj2rg.zip .\MQRT\
move bakatono.zip .\MQRT\
move bakuhatu.zip .\MQRT\
move bananadr.zip .\MQRT\
move bijokkog.zip .\MQRT\
move bijokkoy.zip .\MQRT\
move ccasino.zip .\MQRT\
move chinmoku.zip .\MQRT\
move citylove.zip .\MQRT\
move club90s.zip .\MQRT\
move club90sa.zip .\MQRT\
move cmehyou.zip .\MQRT\
move crystal2.zip .\MQRT\
move crystalg.zip .\MQRT\
move daiyogen.zip .\MQRT\
move dokyusei.zip .\MQRT\
move dokyusp.zip .\MQRT\
move dondenmj.zip .\MQRT\
move finalbny.zip .\MQRT\
move fromanc2.zip .\MQRT\
move fromanc4.zip .\MQRT\
move fromance.zip .\MQRT\
move fromancr.zip .\MQRT\
move gakusai2.zip .\MQRT\
move gakusai.zip .\MQRT\
move gal10ren.zip .\MQRT\
move galkaika.zip .\MQRT\
move galkoku.zip .\MQRT\
move hanamomo.zip .\MQRT\
move hgkairak.zip .\MQRT\
move hotgmck3.zip .\MQRT\
move hotgmck.zip .\MQRT\
move hourouki.zip .\MQRT\
move housemn2.zip .\MQRT\
move housemnq.zip .\MQRT\
move hyouban.zip .\MQRT\
move hypreac2.zip .\MQRT\
move hypreact.zip .\MQRT\
move idhimitu.zip .\MQRT\
move idolmj.zip .\MQRT\
move iemoto.zip .\MQRT\
move imekura.zip .\MQRT\
move janjans1.zip .\MQRT\
move janshin.zip .\MQRT\
move jjparad2.zip .\MQRT\
move jjparads.zip .\MQRT\
move jogakuen.zip .\MQRT\
move kaguya.zip .\MQRT\
move kanatuen.zip .\MQRT\
move kirarast.zip .\MQRT\
move koinomp.zip .\MQRT\
move korinai.zip .\MQRT\
move lemnangl.zip .\MQRT\
move mahretsu.zip .\MQRT\
move majs101b.zip .\MQRT\
move marukin.zip .\MQRT\
move mayumi.zip .\MQRT\
move mcnpshnt.zip .\MQRT\
move mcontest.zip .\MQRT\
move mfunclub.zip .\MQRT\
move mgakuen2.zip .\MQRT\
move mgakuen.zip .\MQRT\
move mgmen89.zip .\MQRT\
move mhgaiden.zip .\MQRT\
move mj4simai.zip .\MQRT\
move mjanbari.zip .\MQRT\
move mjangels.zip .\MQRT\
move mjcamera.zip .\MQRT\
move mjclinic.zip .\MQRT\
move mjderngr.zip .\MQRT\
move mjdialq2.zip .\MQRT\
move mjdiplob.zip .\MQRT\
move mjegolf.zip .\MQRT\
move mjfocus.zip .\MQRT\
move mjfocusm.zip .\MQRT\
move mjfriday.zip .\MQRT\
move mjgottsu.zip .\MQRT\
move mjhokite.zip .\MQRT\
move mjikaga.zip .\MQRT\
move mjkinjas.zip .\MQRT\
move mjkjidai.zip .\MQRT\
move mjkoiura.zip .\MQRT\
move mjkojink.zip .\MQRT\
move mjlaman.zip .\MQRT\
move mjlstory.zip .\MQRT\
move mjnanpaa.zip .\MQRT\
move mjnanpas.zip .\MQRT\
move mjnanpau.zip .\MQRT\
move mjnatsu.zip .\MQRT\
move mjnquest.zip .\MQRT\
move mjsikakb.zip .\MQRT\
move mjsikaku.zip .\MQRT\
move mjsister.zip .\MQRT\
move mjuraden.zip .\MQRT\
move mjyougo.zip .\MQRT\
move mjyuugi.zip .\MQRT\
move mjyuugia.zip .\MQRT\
move mkeibaou.zip .\MQRT\
move mladyhtr.zip .\MQRT\
move mmcamera.zip .\MQRT\
move mmehyou.zip .\MQRT\
move mrokumei.zip .\MQRT\
move mscoutm.zip .\MQRT\
move msjiken.zip .\MQRT\
move natsuiro.zip .\MQRT\
move nekkyoku.zip .\MQRT\
move ngpgal.zip .\MQRT\
move nmsengen.zip .\MQRT\
move ntopstar.zip .\MQRT\
move ojanko2.zip .\MQRT\
move ojankoc.zip .\MQRT\
move ojankohs.zip .\MQRT\
move ojankoy.zip .\MQRT\
move ojousan.zip .\MQRT\
move orangec.zip .\MQRT\
move otatidai.zip .\MQRT\
move otonano.zip .\MQRT\
move pachiten.zip .\MQRT\
move pastelgl.zip .\MQRT\
move patimono.zip .\MQRT\
move peepshow.zip .\MQRT\
move ponchin.zip .\MQRT\
move ponchina.zip .\MQRT\
move psailor1.zip .\MQRT\
move psailor2.zip .\MQRT\
move pstadium.zip .\MQRT\
move qmhayaku.zip .\MQRT\
move renaiclb.zip .\MQRT\
move rmhaihai.zip .\MQRT\
move rmhaihib.zip .\MQRT\
move rmhaijin.zip .\MQRT\
move rmhaisei.zip .\MQRT\
move ryouran.zip .\MQRT\
move sailorwr.zip .\MQRT\
move sailorws.zip .\MQRT\
move scandal.zip .\MQRT\
move scandalm.zip .\MQRT\
move secolove.zip .\MQRT\
move seiha.zip .\MQRT\
move seiham.zip .\MQRT\
move srmp2.zip .\MQRT\
move srmp3.zip .\MQRT\
move srmp4.zip .\MQRT\
move srmp4o.zip .\MQRT\
move srmp7.zip .\MQRT\
move teljan.zip .\MQRT\
move telmahjn.zip .\MQRT\
move themj.zip .\MQRT\
move tokimbsj.zip .\MQRT\
move tokyogal.zip .\MQRT\
move tontonb.zip .\MQRT\
move triplew1.zip .\MQRT\
move triplew2.zip .\MQRT\
move uchuuai.zip .\MQRT\
move ultramhm.zip .\MQRT\
move vanilla.zip .\MQRT\
move vipclub.zip .\MQRT\
move vitaminc.zip .\MQRT\
move yarunara.zip .\MQRT\
move othellos.zip .\MQRT\
move blockgal.zip .\MQRT\
move glass.zip .\MQRT\
move sshangha.zip .\MQRT\
move suzume.zip .\MQRT\
move tgtball.zip .\MQRT\
move tmmjprd.zip .\MQRT\
