;===========================================
; Create folder and move all clones into it.
;===========================================

md CLONES

move puckmana.zip .\CLONES\
move pacman.zip .\CLONES\
move puckmod.zip .\CLONES\
move pacmod.zip .\CLONES\
move hangly.zip .\CLONES\
move hangly2.zip .\CLONES\
move hangly3.zip .\CLONES\
move newpuckx.zip .\CLONES\
move pacheart.zip .\CLONES\
move joyman.zip .\CLONES\
move newpuc2.zip .\CLONES\
move newpuc2b.zip .\CLONES\
move piranha.zip .\CLONES\
move piranhao.zip .\CLONES\
move piranhah.zip .\CLONES\
move nmouseb.zip .\CLONES\
move mspacmab.zip .\CLONES\
move mspacmat.zip .\CLONES\
move mspacpls.zip .\CLONES\
move pacgal.zip .\CLONES\
move mschamp.zip .\CLONES\
move maketrax.zip .\CLONES\
move maketrxb.zip .\CLONES\
move korosuke.zip .\CLONES\
move crush2.zip .\CLONES\
move crush3.zip .\CLONES\
move mbrush.zip .\CLONES\
move paintrlr.zip .\CLONES\
move eyes2.zip .\CLONES\
move gorkans.zip .\CLONES\
move ponpokov.zip .\CLONES\
move theglobp.zip .\CLONES\
move beastf.zip .\CLONES\
move acitya.zip .\CLONES\
move vanvank.zip .\CLONES\
move alibabab.zip .\CLONES\
move pengo2.zip .\CLONES\
move pengo2u.zip .\CLONES\
move pengo3u.zip .\CLONES\
move pengob.zip .\CLONES\
move penta.zip .\CLONES\
move 8bpm.zip .\CLONES\
move theglob.zip .\CLONES\
move theglob2.zip .\CLONES\
move theglob3.zip .\CLONES\
move galaxiaj.zip .\CLONES\
move galmidw.zip .\CLONES\
move galmidwo.zip .\CLONES\
move superg.zip .\CLONES\
move galapx.zip .\CLONES\
move moonaln.zip .\CLONES\
move galap1.zip .\CLONES\
move galap4.zip .\CLONES\
move galturbo.zip .\CLONES\
move swarm.zip .\CLONES\
move zerotime.zip .\CLONES\
move tst_galx.zip .\CLONES\
move piscesb.zip .\CLONES\
move gteikoku.zip .\CLONES\
move gteikokb.zip .\CLONES\
move gteikob2.zip .\CLONES\
move spacbatt.zip .\CLONES\
move skyraidr.zip .\CLONES\
move batman2.zip .\CLONES\
move exodus.zip .\CLONES\
move pacmanbl.zip .\CLONES\
move devilfsg.zip .\CLONES\
move zigzag2.zip .\CLONES\
move jumpbugb.zip .\CLONES\
move mooncrgx.zip .\CLONES\
move mooncrsu.zip .\CLONES\
move mooncrsa.zip .\CLONES\
move mooncrsg.zip .\CLONES\
move smooncrs.zip .\CLONES\
move mooncrsb.zip .\CLONES\
move mooncrs2.zip .\CLONES\
move fantazia.zip .\CLONES\
move mshuttlj.zip .\CLONES\
move moonal2b.zip .\CLONES\
move eagle.zip .\CLONES\
move eagle2.zip .\CLONES\
move checkmaj.zip .\CLONES\
move kingbalj.zip .\CLONES\
move frogg.zip .\CLONES\
move bagmanmc.zip .\CLONES\
move dkongjrm.zip .\CLONES\
move ladybugg.zip .\CLONES\
move vpool.zip .\CLONES\
move drivfrcg.zip .\CLONES\
move scrambls.zip .\CLONES\
move scramblb.zip .\CLONES\
move explorer.zip .\CLONES\
move atlants2.zip .\CLONES\
move theends.zip .\CLONES\
move omega.zip .\CLONES\
move ckongs.zip .\CLONES\
move froggers.zip .\CLONES\
move amidars.zip .\CLONES\
move knockout.zip .\CLONES\
move 800fath.zip .\CLONES\
move mrkougr2.zip .\CLONES\
move mrkougb.zip .\CLONES\
move hunchbks.zip .\CLONES\
move mimonscr.zip .\CLONES\
move mimonsco.zip .\CLONES\
move scobras.zip .\CLONES\
move scobrase.zip .\CLONES\
move scobrab.zip .\CLONES\
move stratgys.zip .\CLONES\
move armorca2.zip .\CLONES\
move moonwara.zip .\CLONES\
move tazmani2.zip .\CLONES\
move aponow.zip .\CLONES\
move losttmbh.zip .\CLONES\
move billiard.zip .\CLONES\
move hustlerb.zip .\CLONES\
move frogseg1.zip .\CLONES\
move frogseg2.zip .\CLONES\
move froggrmc.zip .\CLONES\
move amidaru.zip .\CLONES\
move amidaro.zip .\CLONES\
move amigo.zip .\CLONES\
move turpin.zip .\CLONES\
move 600.zip .\CLONES\
move flyboyb.zip .\CLONES\
move fastfred.zip .\CLONES\
move cclimbrj.zip .\CLONES\
move ccboot.zip .\CLONES\
move ccboot2.zip .\CLONES\
move ckonga.zip .\CLONES\
move ckongjeu.zip .\CLONES\
move ckongo.zip .\CLONES\
move ckongalc.zip .\CLONES\
move monkeyd.zip .\CLONES\
move silvland.zip .\CLONES\
move yamato2.zip .\CLONES\
move swimmera.zip .\CLONES\
move swimmerb.zip .\CLONES\
move rugrats.zip .\CLONES\
move friskyta.zip .\CLONES\
move sectrzon.zip .\CLONES\
move cop01a.zip .\CLONES\
move terracrb.zip .\CLONES\
move terracra.zip .\CLONES\
move amatelas.zip .\CLONES\
move horekidb.zip .\CLONES\
move galivan2.zip .\CLONES\
move dangar2.zip .\CLONES\
move dangarb.zip .\CLONES\
move youma.zip .\CLONES\
move legiono.zip .\CLONES\
move terrafu.zip .\CLONES\
move seiham.zip .\CLONES\
move vipclub.zip .\CLONES\
move mjsikakb.zip .\CLONES\
move mmcamera.zip .\CLONES\
move mjfocusm.zip .\CLONES\
move peepshow.zip .\CLONES\
move scandalm.zip .\CLONES\
move mjnanpaa.zip .\CLONES\
move mjnanpau.zip .\CLONES\
move club90sa.zip .\CLONES\
move finalbny.zip .\CLONES\
move hyouban.zip .\CLONES\
move tokimbsj.zip .\CLONES\
move sailorwr.zip .\CLONES\
move bakuhatu.zip .\CLONES\
move phoenixa.zip .\CLONES\
move phoenixt.zip .\CLONES\
move phoenix3.zip .\CLONES\
move phoenixc.zip .\CLONES\
move condor.zip .\CLONES\
move falcon.zip .\CLONES\
move vautour.zip .\CLONES\
move pleiadbl.zip .\CLONES\
move pleiadce.zip .\CLONES\
move capitol.zip .\CLONES\
move naughtya.zip .\CLONES\
move naughtyc.zip .\CLONES\
move popflama.zip .\CLONES\
move popflamb.zip .\CLONES\
move geebeeg.zip .\CLONES\
move kaitein.zip .\CLONES\
move warpwarr.zip .\CLONES\
move warpwar2.zip .\CLONES\
move rallyxm.zip .\CLONES\
move junglers.zip .\CLONES\
move tactcan2.zip .\CLONES\
move gutangtn.zip .\CLONES\
move cottong.zip .\CLONES\
move boscoo.zip .\CLONES\
move boscoo2.zip .\CLONES\
move boscomd.zip .\CLONES\
move boscomdo.zip .\CLONES\
move galagamw.zip .\CLONES\
move galagamk.zip .\CLONES\
move galagamf.zip .\CLONES\
move galagao.zip .\CLONES\
move gallag.zip .\CLONES\
move nebulbee.zip .\CLONES\
move gatsbee.zip .\CLONES\
move digdugb.zip .\CLONES\
move digdugat.zip .\CLONES\
move digduga1.zip .\CLONES\
move dzigzag.zip .\CLONES\
move xeviousa.zip .\CLONES\
move xeviousb.zip .\CLONES\
move xeviousc.zip .\CLONES\
move xevios.zip .\CLONES\
move battles.zip .\CLONES\
move sxevious.zip .\CLONES\
move superpcm.zip .\CLONES\
move pacnpal2.zip .\CLONES\
move pacnchmp.zip .\CLONES\
move mappyj.zip .\CLONES\
move digdug2o.zip .\CLONES\
move todruago.zip .\CLONES\
move grobda2.zip .\CLONES\
move grobda3.zip .\CLONES\
move gaplusa.zip .\CLONES\
move gapluso.zip .\CLONES\
move galaga3.zip .\CLONES\
move galaga3m.zip .\CLONES\
move galaga3a.zip .\CLONES\
move poleposa.zip .\CLONES\
move polepos1.zip .\CLONES\
move topracer.zip .\CLONES\
move poleps2a.zip .\CLONES\
move poleps2b.zip .\CLONES\
move pacland2.zip .\CLONES\
move pacland3.zip .\CLONES\
move paclandm.zip .\CLONES\
move skykido.zip .\CLONES\
move skykidd.zip .\CLONES\
move baraduka.zip .\CLONES\
move metrocra.zip .\CLONES\
move skykiddo.zip .\CLONES\
move rthundro.zip .\CLONES\
move tceptor2.zip .\CLONES\
move youkaidk.zip .\CLONES\
move yokaidko.zip .\CLONES\
move dspirito.zip .\CLONES\
move pacmanij.zip .\CLONES\
move galag88b.zip .\CLONES\
move galag88j.zip .\CLONES\
move beraboho.zip .\CLONES\
move romperso.zip .\CLONES\
move ws89.zip .\CLONES\
move ws90.zip .\CLONES\
move soukobdx.zip .\CLONES\
move tankfrcj.zip .\CLONES\
move finalapd.zip .\CLONES\
move finalapc.zip .\CLONES\
move finlapjc.zip .\CLONES\
move finlapjb.zip .\CLONES\
move assaultj.zip .\CLONES\
move assaultp.zip .\CLONES\
move marvlanj.zip .\CLONES\
move kyukaido.zip .\CLONES\
move dsaberj.zip .\CLONES\
move finalp2j.zip .\CLONES\
move rthun2j.zip .\CLONES\
move sgunnr2j.zip .\CLONES\
move cosmognj.zip .\CLONES\
move finalp3a.zip .\CLONES\
move suzuk8hj.zip .\CLONES\
move sws92g.zip .\CLONES\
move cgangpzj.zip .\CLONES\
move fa.zip .\CLONES\
move knckhedj.zip .\CLONES\
move emerldaa.zip .\CLONES\
move numanatj.zip .\CLONES\
move nebulryj.zip .\CLONES\
move gunbulet.zip .\CLONES\
move outfxesj.zip .\CLONES\
move ncv1j.zip .\CLONES\
move ncv1j2.zip .\CLONES\
move ncv2j.zip .\CLONES\
move aircombu.zip .\CLONES\
move alpinerc.zip .\CLONES\
move cosmica2.zip .\CLONES\
move panic2.zip .\CLONES\
move panic3.zip .\CLONES\
move panich.zip .\CLONES\
move panicger.zip .\CLONES\
move redclask.zip .\CLONES\
move devzone2.zip .\CLONES\
move nomnlndg.zip .\CLONES\
move ladybugb.zip .\CLONES\
move dorodon2.zip .\CLONES\
move mrdoy.zip .\CLONES\
move mrdot.zip .\CLONES\
move mrdofix.zip .\CLONES\
move mrlo.zip .\CLONES\
move mrdu.zip .\CLONES\
move yankeedo.zip .\CLONES\
move docastl2.zip .\CLONES\
move docastlo.zip .\CLONES\
move douni.zip .\CLONES\
move dorunru2.zip .\CLONES\
move dorunruc.zip .\CLONES\
move spiero.zip .\CLONES\
move dkongpe.zip .\CLONES\
move dkongo.zip .\CLONES\
move dkongjp.zip .\CLONES\
move dkongjo.zip .\CLONES\
move dkongjo1.zip .\CLONES\
move dkongx.zip .\CLONES\
move dkrdemo.zip .\CLONES\
move dkongjrj.zip .\CLONES\
move dkngjnrj.zip .\CLONES\
move dkongjrb.zip .\CLONES\
move dkngjnrb.zip .\CLONES\
move dkong3j.zip .\CLONES\
move dkong3b.zip .\CLONES\
move mariojp.zip .\CLONES\
move masao.zip .\CLONES\
move pestplce.zip .\CLONES\
move 8ballat2.zip .\CLONES\
move hunchbkd.zip .\CLONES\
move sbdk.zip .\CLONES\
move herbiedk.zip .\CLONES\
move herodk.zip .\CLONES\
move herodku.zip .\CLONES\
move popeyeu.zip .\CLONES\
move popeyef.zip .\CLONES\
move popeyebl.zip .\CLONES\
move spnchotj.zip .\CLONES\
move pc_grdue.zip .\CLONES\
move excitbkj.zip .\CLONES\
move iceclmbj.zip .\CLONES\
move machridj.zip .\CLONES\
move rbibba.zip .\CLONES\
move smgolfj.zip .\CLONES\
move vspinblj.zip .\CLONES\
move vsbballj.zip .\CLONES\
move vsbbalja.zip .\CLONES\
move smgolfb.zip .\CLONES\
move vsbbaljb.zip .\CLONES\
move dplay.zip .\CLONES\
move clowns1.zip .\CLONES\
move invaddlx.zip .\CLONES\
move moonbase.zip .\CLONES\
move earthinv.zip .\CLONES\
move spaceatt.zip .\CLONES\
move spaceat2.zip .\CLONES\
move sinvzen.zip .\CLONES\
move superinv.zip .\CLONES\
move sinvemag.zip .\CLONES\
move jspecter.zip .\CLONES\
move jspectr2.zip .\CLONES\
move invrvnga.zip .\CLONES\
move galxwar2.zip .\CLONES\
move galxwart.zip .\CLONES\
move starw.zip .\CLONES\
move grescue.zip .\CLONES\
move desterth.zip .\CLONES\
move cosmicmo.zip .\CLONES\
move bandido.zip .\CLONES\
move ozmawar2.zip .\CLONES\
move solfight.zip .\CLONES\
move spaceph.zip .\CLONES\
move schasrcv.zip .\CLONES\
move helifira.zip .\CLONES\
move sfeverbw.zip .\CLONES\
move laser.zip .\CLONES\
move spcewarl.zip .\CLONES\
move polarisa.zip .\CLONES\
move alieninv.zip .\CLONES\
move tst_invd.zip .\CLONES\
move sitv.zip .\CLONES\
move sicv.zip .\CLONES\
move sisv.zip .\CLONES\
move sisv2.zip .\CLONES\
move spacewr3.zip .\CLONES\
move invaderl.zip .\CLONES\
move spceking.zip .\CLONES\
move spcewars.zip .\CLONES\
move 8ball1.zip .\CLONES\
move radarzn1.zip .\CLONES\
move radarznt.zip .\CLONES\
move outline.zip .\CLONES\
move gorfpgm1.zip .\CLONES\
move kicka.zip .\CLONES\
move shollow2.zip .\CLONES\
move tron2.zip .\CLONES\
move tronfp.zip .\CLONES\
move twotigra.zip .\CLONES\
move tappera.zip .\CLONES\
move sutapper.zip .\CLONES\
move rbtapper.zip .\CLONES\
move dotrona.zip .\CLONES\
move dotrone.zip .\CLONES\
move demoderm.zip .\CLONES\
move rampage2.zip .\CLONES\
move spyhnt2a.zip .\CLONES\
move archriv2.zip .\CLONES\
move minigol2.zip .\CLONES\
move rescrdsa.zip .\CLONES\
move mpatrolw.zip .\CLONES\
move vsyard.zip .\CLONES\
move vsyard2.zip .\CLONES\
move motorace.zip .\CLONES\
move atomboy.zip .\CLONES\
move kungfud.zip .\CLONES\
move spartanx.zip .\CLONES\
move kungfub.zip .\CLONES\
move kungfub2.zip .\CLONES\
move ldruna.zip .\CLONES\
move ldrun3jp.zip .\CLONES\
move yanchamr.zip .\CLONES\
move spelnkrj.zip .\CLONES\
move vigilntu.zip .\CLONES\
move vigilntj.zip .\CLONES\
move rtypepj.zip .\CLONES\
move rtypeu.zip .\CLONES\
move mrheli.zip .\CLONES\
move nspiritj.zip .\CLONES\
move rtype2j.zip .\CLONES\
move hharryu.zip .\CLONES\
move dkgensan.zip .\CLONES\
move dkgenm72.zip .\CLONES\
move poundfou.zip .\CLONES\
move gallop.zip .\CLONES\
move sichuana.zip .\CLONES\
move shisen.zip .\CLONES\
move matchit.zip .\CLONES\
move dynablsb.zip .\CLONES\
move bombrman.zip .\CLONES\
move bbmanwj.zip .\CLONES\
move atompunk.zip .\CLONES\
move gussun.zip .\CLONES\
move shisen2.zip .\CLONES\
move gunforcu.zip .\CLONES\
move gunforcj.zip .\CLONES\
move thndblst.zip .\CLONES\
move uccopsar.zip .\CLONES\
move uccopsj.zip .\CLONES\
move gunhohki.zip .\CLONES\
move skingame.zip .\CLONES\
move skingam2.zip .\CLONES\
move hooku.zip .\CLONES\
move hookj.zip .\CLONES\
move rtypelej.zip .\CLONES\
move inthuntu.zip .\CLONES\
move kaiteids.zip .\CLONES\
move leaguemn.zip .\CLONES\
move psoldier.zip .\CLONES\
move dsccr94j.zip .\CLONES\
move geostorm.zip .\CLONES\
move mplanuk.zip .\CLONES\
move qbertjp.zip .\CLONES\
move myqbert.zip .\CLONES\
move qberttst.zip .\CLONES\
move qixa.zip .\CLONES\
move qixb.zip .\CLONES\
move qix2.zip .\CLONES\
move elecyoy2.zip .\CLONES\
move kram2.zip .\CLONES\
move kram3.zip .\CLONES\
move zookeep2.zip .\CLONES\
move zookeep3.zip .\CLONES\
move slithera.zip .\CLONES\
move junglkj2.zip .\CLONES\
move jungleh.zip .\CLONES\
move junglhbr.zip .\CLONES\
move piratpet.zip .\CLONES\
move alpinea.zip .\CLONES\
move wwester1.zip .\CLONES\
move elevatob.zip .\CLONES\
move crbalon2.zip .\CLONES\
move lkageb.zip .\CLONES\
move lkageb2.zip .\CLONES\
move lkageb3.zip .\CLONES\
move retofin1.zip .\CLONES\
move retofin2.zip .\CLONES\
move rollace.zip .\CLONES\
move rollace2.zip .\CLONES\
move ringfgt.zip .\CLONES\
move ringfgt2.zip .\CLONES\
move undoukai.zip .\CLONES\
move tsamura2.zip .\CLONES\
move m660j.zip .\CLONES\
move m660b.zip .\CLONES\
move alphaxz.zip .\CLONES\
move buggycht.zip .\CLONES\
move flstoryj.zip .\CLONES\
move onna34ra.zip .\CLONES\
move ogonsiro.zip .\CLONES\
move halleysc.zip .\CLONES\
move halleycj.zip .\CLONES\
move storming.zip .\CLONES\
move tokiob.zip .\CLONES\
move bublbob1.zip .\CLONES\
move bublbobr.zip .\CLONES\
move bubbobr1.zip .\CLONES\
move bublboblp.zip .\CLONES\
move boblbobl.zip .\CLONES\
move sboblbob.zip .\CLONES\
move bublboblu.zip .\CLONES\
move bublcave.zip .\CLONES\
move missb2.zip .\CLONES\
move mexico86.zip .\CLONES\
move dariusj.zip .\CLONES\
move dariuso.zip .\CLONES\
move dariuse.zip .\CLONES\
move rastanu.zip .\CLONES\
move rastanu2.zip .\CLONES\
move rastsaga.zip .\CLONES\
move topspedu.zip .\CLONES\
move fullthrl.zip .\CLONES\
move opwolfb.zip .\CLONES\
move othundu.zip .\CLONES\
move rainbowo.zip .\CLONES\
move rainbowe.zip .\CLONES\
move jumping.zip .\CLONES\
move arknoidu.zip .\CLONES\
move arknoiuo.zip .\CLONES\
move arknoidj.zip .\CLONES\
move arkbl2.zip .\CLONES\
move arkbl3.zip .\CLONES\
move paddle2.zip .\CLONES\
move arkatayt.zip .\CLONES\
move arkblock.zip .\CLONES\
move arkbloc2.zip .\CLONES\
move arkangc.zip .\CLONES\
move arkatour.zip .\CLONES\
move sqixbl.zip .\CLONES\
move volfiedu.zip .\CLONES\
move volfiedj.zip .\CLONES\
move bonzeadu.zip .\CLONES\
move jigkmgri.zip .\CLONES\
move cadashj.zip .\CLONES\
move cadashu.zip .\CLONES\
move cadashi.zip .\CLONES\
move cadashf.zip .\CLONES\
move wgpj.zip .\CLONES\
move wgpjoy.zip .\CLONES\
move wgpjoya.zip .\CLONES\
move wgp2.zip .\CLONES\
move opwolf3u.zip .\CLONES\
move ninjawj.zip .\CLONES\
move darius2d.zip .\CLONES\
move drius2do.zip .\CLONES\
move twinhwku.zip .\CLONES\
move daisenpu.zip .\CLONES\
move arknid2u.zip .\CLONES\
move arknid2j.zip .\CLONES\
move drtopplu.zip .\CLONES\
move drtopplj.zip .\CLONES\
move kagekij.zip .\CLONES\
move chukatau.zip .\CLONES\
move chukataj.zip .\CLONES\
move tnzsb.zip .\CLONES\
move tnzs2.zip .\CLONES\
move kurikinu.zip .\CLONES\
move kurikinj.zip .\CLONES\
move kurikina.zip .\CLONES\
move fhawkj.zip .\CLONES\
move champwru.zip .\CLONES\
move champwrj.zip .\CLONES\
move tubeit.zip .\CLONES\
move nastarw.zip .\CLONES\
move rastsag2.zip .\CLONES\
move rambo3ae.zip .\CLONES\
move rambo3a.zip .\CLONES\
move crimecu.zip .\CLONES\
move crimecj.zip .\CLONES\
move tetrist.zip .\CLONES\
move ashurau.zip .\CLONES\
move silentdj.zip .\CLONES\
move spacedxj.zip .\CLONES\
move spacedxo.zip .\CLONES\
move contcrcu.zip .\CLONES\
move chasehqj.zip .\CLONES\
move scia.zip .\CLONES\
move sciu.zip .\CLONES\
move bsharkj.zip .\CLONES\
move bsharkjjs.zip .\CLONES\
move aquajckj.zip .\CLONES\
move pwheelsj.zip .\CLONES\
move undrfiru.zip .\CLONES\
move undrfirj.zip .\CLONES\
move finalbj.zip .\CLONES\
move dondokdu.zip .\CLONES\
move dondokdj.zip .\CLONES\
move megabj.zip .\CLONES\
move thndfoxu.zip .\CLONES\
move thndfoxj.zip .\CLONES\
move camltrua.zip .\CLONES\
move cameltrj.zip .\CLONES\
move liquidku.zip .\CLONES\
move mizubaku.zip .\CLONES\
move majest12.zip .\CLONES\
move gunfronj.zip .\CLONES\
move growlu.zip .\CLONES\
move runark.zip .\CLONES\
move mjnquesb.zip .\CLONES\
move hthero.zip .\CLONES\
move euroch92.zip .\CLONES\
move ninjakj.zip .\CLONES\
move pulirulj.zip .\CLONES\
move metalbj.zip .\CLONES\
move deadconj.zip .\CLONES\
move dinorexj.zip .\CLONES\
move dinorexu.zip .\CLONES\
move driveout.zip .\CLONES\
move ringragj.zip .\CLONES\
move ringragu.zip .\CLONES\
move arabiamj.zip .\CLONES\
move arabiamu.zip .\CLONES\
move ridefgtj.zip .\CLONES\
move ridefgtu.zip .\CLONES\
move gseekerj.zip .\CLONES\
move gseekeru.zip .\CLONES\
move hthero93.zip .\CLONES\
move cupfinal.zip .\CLONES\
move trstarj.zip .\CLONES\
move prmtmfgt.zip .\CLONES\
move trstaro.zip .\CLONES\
move trstaroj.zip .\CLONES\
move prmtmfgo.zip .\CLONES\
move rayforcj.zip .\CLONES\
move rayforce.zip .\CLONES\
move intcup94.zip .\CLONES\
move lightbr.zip .\CLONES\
move dungenmu.zip .\CLONES\
move kaiserkj.zip .\CLONES\
move gblchmp.zip .\CLONES\
move dankuga.zip .\CLONES\
move dariusgj.zip .\CLONES\
move dariusgu.zip .\CLONES\
move dariusgx.zip .\CLONES\
move bubsympe.zip .\CLONES\
move bubsympu.zip .\CLONES\
move bubsymph.zip .\CLONES\
move spcinvdj.zip .\CLONES\
move hthero95.zip .\CLONES\
move hthro95u.zip .\CLONES\
move elvactrj.zip .\CLONES\
move elvact2u.zip .\CLONES\
move spcnv95u.zip .\CLONES\
move akkanvdr.zip .\CLONES\
move pbobbl2j.zip .\CLONES\
move pbobbl2u.zip .\CLONES\
move pbobbl2x.zip .\CLONES\
move bubblemj.zip .\CLONES\
move pbobbl3u.zip .\CLONES\
move pbobbl3j.zip .\CLONES\
move pbobbl4j.zip .\CLONES\
move pbobbl4u.zip .\CLONES\
move popnpopj.zip .\CLONES\
move popnpopu.zip .\CLONES\
move landmkrp.zip .\CLONES\
move perfrmau.zip .\CLONES\
move tigerh2.zip .\CLONES\
move tigerhj.zip .\CLONES\
move tigerhb1.zip .\CLONES\
move tigerhb2.zip .\CLONES\
move slapbtjp.zip .\CLONES\
move slapbtuk.zip .\CLONES\
move alcon.zip .\CLONES\
move getstarj.zip .\CLONES\
move getstarb.zip .\CLONES\
move skyshark.zip .\CLONES\
move hishouza.zip .\CLONES\
move fsharkbt.zip .\CLONES\
move pyros.zip .\CLONES\
move wardnerj.zip .\CLONES\
move twincobu.zip .\CLONES\
move ktiger.zip .\CLONES\
move hellfir1.zip .\CLONES\
move demonwl1.zip .\CLONES\
move samesame.zip .\CLONES\
move samesam2.zip .\CLONES\
move outzonea.zip .\CLONES\
move vimana1.zip .\CLONES\
move vimanan.zip .\CLONES\
move snowbroa.zip .\CLONES\
move snowbrob.zip .\CLONES\
move snowbroj.zip .\CLONES\
move wintbob.zip .\CLONES\
move bcstrya.zip .\CLONES\
move hyperpcb.zip .\CLONES\
move whoopee.zip .\CLONES\
move pipibibi.zip .\CLONES\
move fixeighb.zip .\CLONES\
move grindstm.zip .\CLONES\
move grindsta.zip .\CLONES\
move batugnsp.zip .\CLONES\
move sstriker.zip .\CLONES\
move kingdmgp.zip .\CLONES\
move battlega.zip .\CLONES\
move battlegb.zip .\CLONES\
move batridra.zip .\CLONES\
move batridrk.zip .\CLONES\
move bbakradu.zip .\CLONES\
move donpachj.zip .\CLONES\
move donpachk.zip .\CLONES\
move nmaster.zip .\CLONES\
move sailormo.zip .\CLONES\
move ddonpchj.zip .\CLONES\
move espradej.zip .\CLONES\
move espradeo.zip .\CLONES\
move guwanges.zip .\CLONES\
move repulse.zip .\CLONES\
move 99lstwar.zip .\CLONES\
move 99lstwra.zip .\CLONES\
move skywolf.zip .\CLONES\
move skywolf2.zip .\CLONES\
move defendg.zip .\CLONES\
move defendw.zip .\CLONES\
move defndjeu.zip .\CLONES\
move defcmnd.zip .\CLONES\
move defence.zip .\CLONES\
move maydaya.zip .\CLONES\
move maydayb.zip .\CLONES\
move colony7a.zip .\CLONES\
move robotryo.zip .\CLONES\
move joustr.zip .\CLONES\
move joustwr.zip .\CLONES\
move bubblesr.zip .\CLONES\
move bubblesp.zip .\CLONES\
move sinista1.zip .\CLONES\
move sinista2.zip .\CLONES\
move blastkit.zip .\CLONES\
move vulgus2.zip .\CLONES\
move vulgusj.zip .\CLONES\
move sonsonj.zip .\CLONES\
move 1942a.zip .\CLONES\
move 1942b.zip .\CLONES\
move savgbees.zip .\CLONES\
move commandu.zip .\CLONES\
move commandj.zip .\CLONES\
move sinvasn.zip .\CLONES\
move sinvasnb.zip .\CLONES\
move gnga.zip .\CLONES\
move gngt.zip .\CLONES\
move makaimur.zip .\CLONES\
move makaimuc.zip .\CLONES\
move makaimug.zip .\CLONES\
move gunsmoku.zip .\CLONES\
move gunsmoka.zip .\CLONES\
move gunsmokj.zip .\CLONES\
move sctionza.zip .\CLONES\
move trojanr.zip .\CLONES\
move trojanj.zip .\CLONES\
move srumblr2.zip .\CLONES\
move rushcrsh.zip .\CLONES\
move lwings2.zip .\CLONES\
move lwingsjp.zip .\CLONES\
move sidearmr.zip .\CLONES\
move sidearjp.zip .\CLONES\
move dygera.zip .\CLONES\
move avenger2.zip .\CLONES\
move buraiken.zip .\CLONES\
move bionicc2.zip .\CLONES\
move topsecrt.zip .\CLONES\
move 1943j.zip .\CLONES\
move bktigerb.zip .\CLONES\
move blkdrgon.zip .\CLONES\
move blkdrgnb.zip .\CLONES\
move sf1us.zip .\CLONES\
move sf1jp.zip .\CLONES\
move sf1p.zip .\CLONES\
move toramich.zip .\CLONES\
move f1dreamb.zip .\CLONES\
move lstduela.zip .\CLONES\
move lstduelb.zip .\CLONES\
move madgearj.zip .\CLONES\
move ledstorm.zip .\CLONES\
move lostwrld.zip .\CLONES\
move ghoulsu.zip .\CLONES\
move daimakai.zip .\CLONES\
move stridrua.zip .\CLONES\
move striderj.zip .\CLONES\
move stridrja.zip .\CLONES\
move dwj.zip .\CLONES\
move willowj.zip .\CLONES\
move willowje.zip .\CLONES\
move area88.zip .\CLONES\
move ffightu.zip .\CLONES\
move ffightj.zip .\CLONES\
move ffightj1.zip .\CLONES\
move 1941j.zip .\CLONES\
move mercsu.zip .\CLONES\
move mercsua.zip .\CLONES\
move mercsj.zip .\CLONES\
move chikij.zip .\CLONES\
move mswordr1.zip .\CLONES\
move mswordu.zip .\CLONES\
move mswordj.zip .\CLONES\
move cawingu.zip .\CLONES\
move cawingj.zip .\CLONES\
move nemoj.zip .\CLONES\
move sf2eb.zip .\CLONES\
move sf2ua.zip .\CLONES\
move sf2ub.zip .\CLONES\
move sf2ud.zip .\CLONES\
move sf2ue.zip .\CLONES\
move sf2uf.zip .\CLONES\
move sf2ui.zip .\CLONES\
move sf2uk.zip .\CLONES\
move sf2j.zip .\CLONES\
move sf2ja.zip .\CLONES\
move sf2jc.zip .\CLONES\
move 3wonderu.zip .\CLONES\
move wonder3.zip .\CLONES\
move kodu.zip .\CLONES\
move kodj.zip .\CLONES\
move kodb.zip .\CLONES\
move captcomu.zip .\CLONES\
move captcomj.zip .\CLONES\
move knightsu.zip .\CLONES\
move knightsj.zip .\CLONES\
move sf2ceua.zip .\CLONES\
move sf2ceub.zip .\CLONES\
move sf2ceuc.zip .\CLONES\
move sf2cej.zip .\CLONES\
move sf2rb.zip .\CLONES\
move sf2rb2.zip .\CLONES\
move sf2red.zip .\CLONES\
move sf2v004.zip .\CLONES\
move sf2accp2.zip .\CLONES\
move sf2m1.zip .\CLONES\
move sf2m2.zip .\CLONES\
move sf2m3.zip .\CLONES\
move sf2m4.zip .\CLONES\
move sf2m5.zip .\CLONES\
move sf2m6.zip .\CLONES\
move sf2m7.zip .\CLONES\
move sf2yyc.zip .\CLONES\
move sf2koryu.zip .\CLONES\
move varthu.zip .\CLONES\
move varthj.zip .\CLONES\
move wofa.zip .\CLONES\
move wofu.zip .\CLONES\
move wofj.zip .\CLONES\
move sf2t.zip .\CLONES\
move sf2tj.zip .\CLONES\
move dinou.zip .\CLONES\
move dinoj.zip .\CLONES\
move punishru.zip .\CLONES\
move punishrj.zip .\CLONES\
move slammasu.zip .\CLONES\
move mbomberj.zip .\CLONES\
move mbombrd.zip .\CLONES\
move mbombrdj.zip .\CLONES\
move qadj.zip .\CLONES\
move pang3j.zip .\CLONES\
move rockmanj.zip .\CLONES\
move ssf2u.zip .\CLONES\
move ssf2a.zip .\CLONES\
move ssf2ar1.zip .\CLONES\
move ssf2j.zip .\CLONES\
move ssf2jr1.zip .\CLONES\
move ssf2jr2.zip .\CLONES\
move ssf2tb.zip .\CLONES\
move ssf2tbj.zip .\CLONES\
move ecofghta.zip .\CLONES\
move uecology.zip .\CLONES\
move ddtodu.zip .\CLONES\
move ddtodur1.zip .\CLONES\
move ddtodj.zip .\CLONES\
move ddtoda.zip .\CLONES\
move ddtodh.zip .\CLONES\
move ssf2t.zip .\CLONES\
move ssf2tu.zip .\CLONES\
move ssf2tur1.zip .\CLONES\
move ssf2ta.zip .\CLONES\
move ssf2xj.zip .\CLONES\
move avspu.zip .\CLONES\
move avspj.zip .\CLONES\
move avspa.zip .\CLONES\
move dstlku.zip .\CLONES\
move dstlkur1.zip .\CLONES\
move dstlka.zip .\CLONES\
move vampj.zip .\CLONES\
move vampja.zip .\CLONES\
move vampjr1.zip .\CLONES\
move smbomb.zip .\CLONES\
move smbombr1.zip .\CLONES\
move armwaru.zip .\CLONES\
move pgear.zip .\CLONES\
move pgearr1.zip .\CLONES\
move armwara.zip .\CLONES\
move xmcotau.zip .\CLONES\
move xmcotah.zip .\CLONES\
move xmcotaj.zip .\CLONES\
move xmcotaj1.zip .\CLONES\
move xmcotaa.zip .\CLONES\
move xmcotajr.zip .\CLONES\
move nwarrh.zip .\CLONES\
move nwarrb.zip .\CLONES\
move vhuntj.zip .\CLONES\
move vhuntjr1.zip .\CLONES\
move cybotsj.zip .\CLONES\
move sfar1.zip .\CLONES\
move sfar2.zip .\CLONES\
move sfau.zip .\CLONES\
move sfzj.zip .\CLONES\
move sfzjr1.zip .\CLONES\
move sfzjr2.zip .\CLONES\
move sfzh.zip .\CLONES\
move sfzb.zip .\CLONES\
move mshu.zip .\CLONES\
move mshj.zip .\CLONES\
move msha.zip .\CLONES\
move mshh.zip .\CLONES\
move mshb.zip .\CLONES\
move 19xxj.zip .\CLONES\
move 19xxjr1.zip .\CLONES\
move 19xxa.zip .\CLONES\
move 19xxh.zip .\CLONES\
move ddsomr1.zip .\CLONES\
move ddsomu.zip .\CLONES\
move ddsomur1.zip .\CLONES\
move ddsomjr1.zip .\CLONES\
move ddsomj.zip .\CLONES\
move ddsoma.zip .\CLONES\
move sfz2j.zip .\CLONES\
move sfz2a.zip .\CLONES\
move sfz2b.zip .\CLONES\
move sfz2br1.zip .\CLONES\
move spf2xj.zip .\CLONES\
move megamn2a.zip .\CLONES\
move rckman2j.zip .\CLONES\
move sfz2aj.zip .\CLONES\
move sfz2ah.zip .\CLONES\
move sfz2ab.zip .\CLONES\
move sfz2aa.zip .\CLONES\
move xmvsfu.zip .\CLONES\
move xmvsfur1.zip .\CLONES\
move xmvsfj.zip .\CLONES\
move xmvsfjr1.zip .\CLONES\
move xmvsfjr2.zip .\CLONES\
move xmvsfa.zip .\CLONES\
move xmvsfh.zip .\CLONES\
move xmvsfb.zip .\CLONES\
move batcirj.zip .\CLONES\
move batcira.zip .\CLONES\
move vsavu.zip .\CLONES\
move vsavj.zip .\CLONES\
move vsava.zip .\CLONES\
move vsavh.zip .\CLONES\
move mshvsfu1.zip .\CLONES\
move mshvsfj.zip .\CLONES\
move mshvsfj1.zip .\CLONES\
move mshvsfj2.zip .\CLONES\
move mshvsfh.zip .\CLONES\
move mshvsfa.zip .\CLONES\
move mshvsfa1.zip .\CLONES\
move mshvsfb.zip .\CLONES\
move mshvsfb1.zip .\CLONES\
move csclubj.zip .\CLONES\
move cscluba.zip .\CLONES\
move csclubh.zip .\CLONES\
move pfghtj.zip .\CLONES\
move sgemfa.zip .\CLONES\
move sgemfh.zip .\CLONES\
move vhunt2r1.zip .\CLONES\
move mvscj.zip .\CLONES\
move mvscjr1.zip .\CLONES\
move mvsca.zip .\CLONES\
move mvsch.zip .\CLONES\
move sfa3r1.zip .\CLONES\
move sfz3j.zip .\CLONES\
move sfz3jr1.zip .\CLONES\
move sfz3a.zip .\CLONES\
move gwingj.zip .\CLONES\
move gmahou.zip .\CLONES\
move mmatrixj.zip .\CLONES\
move 1944j.zip .\CLONES\
move progearj.zip .\CLONES\
move ts2j.zip .\CLONES\
move sfexj.zip .\CLONES\
move sfexpj.zip .\CLONES\
move jgakuen.zip .\CLONES\
move kikaioh.zip .\CLONES\
move sfex2p.zip .\CLONES\
move stridr2a.zip .\CLONES\
move shiryu2.zip .\CLONES\
move glprac2j.zip .\CLONES\
move glprac2l.zip .\CLONES\
move jdreddb.zip .\CLONES\
move mgcldtea.zip .\CLONES\
move gdarius2.zip .\CLONES\
move tekkena.zip .\CLONES\
move tekkenb.zip .\CLONES\
move tekken2a.zip .\CLONES\
move tekken2b.zip .\CLONES\
move souledga.zip .\CLONES\
move souledgb.zip .\CLONES\
move 7toitsu.zip .\CLONES\
move pkladiel.zip .\CLONES\
move pangb.zip .\CLONES\
move bbros.zip .\CLONES\
move pompingw.zip .\CLONES\
move sbbros.zip .\CLONES\
move blocka.zip .\CLONES\
move blockj.zip .\CLONES\
move blockbl.zip .\CLONES\
move capbowl2.zip .\CLONES\
move clbowl.zip .\CLONES\
move wfortuna.zip .\CLONES\
move stratab1.zip .\CLONES\
move hstenn10.zip .\CLONES\
move sliksh17.zip .\CLONES\
move pegglet.zip .\CLONES\
move rimrck20.zip .\CLONES\
move rimrck16.zip .\CLONES\
move rimrck12.zip .\CLONES\
move gtg2t.zip .\CLONES\
move gtg2j.zip .\CLONES\
move timek131.zip .\CLONES\
move hardyd10.zip .\CLONES\
move bloods22.zip .\CLONES\
move bloods21.zip .\CLONES\
move bloods11.zip .\CLONES\
move pairsa.zip .\CLONES\
move wcbwl165.zip .\CLONES\
move wcbwl161.zip .\CLONES\
move wcbwl12.zip .\CLONES\
move sftm110.zip .\CLONES\
move sftm111.zip .\CLONES\
move sftmj.zip .\CLONES\
move sshot137.zip .\CLONES\
move quartrba.zip .\CLONES\
move teamqb2.zip .\CLONES\
move aafbd2p.zip .\CLONES\
move aafbc.zip .\CLONES\
move aafbb.zip .\CLONES\
move pigouta.zip .\CLONES\
move ataxxa.zip .\CLONES\
move ataxxj.zip .\CLONES\
move depthv1.zip .\CLONES\
move subhunt.zip .\CLONES\
move sspacat2.zip .\CLONES\
move sspacatc.zip .\CLONES\
move headonb.zip .\CLONES\
move sptrekct.zip .\CLONES\
move carnvckt.zip .\CLONES\
move spacfura.zip .\CLONES\
move elim2a.zip .\CLONES\
move elim4.zip .\CLONES\
move astrob2.zip .\CLONES\
move astrob1.zip .\CLONES\
move pignewta.zip .\CLONES\
move zaxxon2.zip .\CLONES\
move zaxxonb.zip .\CLONES\
move tiptop.zip .\CLONES\
move starjacs.zip .\CLONES\
move reguluso.zip .\CLONES\
move regulusu.zip .\CLONES\
move upndownu.zip .\CLONES\
move mrvikngj.zip .\CLONES\
move flickyo.zip .\CLONES\
move thetogyu.zip .\CLONES\
move ssanchan.zip .\CLONES\
move pitfallu.zip .\CLONES\
move seganinu.zip .\CLONES\
move nprinces.zip .\CLONES\
move nprincso.zip .\CLONES\
move nprincsu.zip .\CLONES\
move nprincsb.zip .\CLONES\
move imsorryj.zip .\CLONES\
move teddybbo.zip .\CLONES\
move sscandal.zip .\CLONES\
move myherok.zip .\CLONES\
move chplftb.zip .\CLONES\
move chplftbl.zip .\CLONES\
move wboyo.zip .\CLONES\
move wboy2.zip .\CLONES\
move wboy2u.zip .\CLONES\
move wboy3.zip .\CLONES\
move wboyu.zip .\CLONES\
move wbdeluxe.zip .\CLONES\
move gardiab.zip .\CLONES\
move blckgalb.zip .\CLONES\
move wbmljo.zip .\CLONES\
move wbmljb.zip .\CLONES\
move wbmlvc.zip .\CLONES\
move wbmlb.zip .\CLONES\
move astrofl.zip .\CLONES\
move turboa.zip .\CLONES\
move turbob.zip .\CLONES\
move buckrogn.zip .\CLONES\
move dotriku2.zip .\CLONES\
move aliensya.zip .\CLONES\
move aliensyb.zip .\CLONES\
move aliensyj.zip .\CLONES\
move astorm2p.zip .\CLONES\
move auraila.zip .\CLONES\
move bayrouta.zip .\CLONES\
move bayrtbl1.zip .\CLONES\
move bayrtbl2.zip .\CLONES\
move goldnaxb.zip .\CLONES\
move goldnaxc.zip .\CLONES\
move goldnaxj.zip .\CLONES\
move jyuohki.zip .\CLONES\
move moonwlka.zip .\CLONES\
move sdioj.zip .\CLONES\
move shinobia.zip .\CLONES\
move shinobib.zip .\CLONES\
move tetrisa.zip .\CLONES\
move wb3a.zip .\CLONES\
move cottona.zip .\CLONES\
move thndrbdj.zip .\CLONES\
move toutruna.zip .\CLONES\
move aburner.zip .\CLONES\
move alexkida.zip .\CLONES\
move altbeas2.zip .\CLONES\
move astormbl.zip .\CLONES\
move dumpmtmt.zip .\CLONES\
move endurob2.zip .\CLONES\
move endurobl.zip .\CLONES\
move eswatbl.zip .\CLONES\
move fantzono.zip .\CLONES\
move fpointbl.zip .\CLONES\
move fpointbj.zip .\CLONES\
move goldnabl.zip .\CLONES\
move goldnaxa.zip .\CLONES\
move moonwlkb.zip .\CLONES\
move outruna.zip .\CLONES\
move outrunb.zip .\CLONES\
move passht4b.zip .\CLONES\
move passshtb.zip .\CLONES\
move quartet2.zip .\CLONES\
move quartt2j.zip .\CLONES\
move quartetj.zip .\CLONES\
move shangonb.zip .\CLONES\
move shdancbl.zip .\CLONES\
move shdancrj.zip .\CLONES\
move shdancrb.zip .\CLONES\
move shinobl.zip .\CLONES\
move tetrisbl.zip .\CLONES\
move tturfbl.zip .\CLONES\
move tturfu.zip .\CLONES\
move wb3bl.zip .\CLONES\
move svs.zip .\CLONES\
move jleague.zip .\CLONES\
move sonicp.zip .\CLONES\
move ga2j.zip .\CLONES\
move spideyj.zip .\CLONES\
move harddunj.zip .\CLONES\
move dnmtdeka.zip .\CLONES\
move finlarch.zip .\CLONES\
move thunt.zip .\CLONES\
move sfish2j.zip .\CLONES\
move croquis.zip .\CLONES\
move bloxeedc.zip .\CLONES\
move columnsj.zip .\CLONES\
move tfrceacj.zip .\CLONES\
move tfrceacb.zip .\CLONES\
move tantrbl.zip .\CLONES\
move tantrbl2.zip .\CLONES\
move puyopuya.zip .\CLONES\
move puyopuyb.zip .\CLONES\
move ichidnte.zip .\CLONES\
move ichidntb.zip .\CLONES\
move pclubjv2.zip .\CLONES\
move pclubjv4.zip .\CLONES\
move pclubjv5.zip .\CLONES\
move btime2.zip .\CLONES\
move btimem.zip .\CLONES\
move cookrace.zip .\CLONES\
move bnj.zip .\CLONES\
move caractn.zip .\CLONES\
move discof.zip .\CLONES\
move ctislnd2.zip .\CLONES\
move ctislnd3.zip .\CLONES\
move csweetht.zip .\CLONES\
move cburnrb2.zip .\CLONES\
move cbnj.zip .\CLONES\
move cgraplp2.zip .\CLONES\
move clapapa2.zip .\CLONES\
move cnights2.zip .\CLONES\
move cscrtry2.zip .\CLONES\
move cppicf2.zip .\CLONES\
move astrof2.zip .\CLONES\
move astrof3.zip .\CLONES\
move tomahaw5.zip .\CLONES\
move liberatb.zip .\CLONES\
move bwings.zip .\CLONES\
move batwings.zip .\CLONES\
move zavigaj.zip .\CLONES\
move karatedo.zip .\CLONES\
move kchampvs.zip .\CLONES\
move karatevs.zip .\CLONES\
move firetpbl.zip .\CLONES\
move brkthruj.zip .\CLONES\
move shootouj.zip .\CLONES\
move shootoub.zip .\CLONES\
move sidepctj.zip .\CLONES\
move sidepctb.zip .\CLONES\
move wexpress.zip .\CLONES\
move wexpresb.zip .\CLONES\
move wexpresc.zip .\CLONES\
move pcktgalb.zip .\CLONES\
move pcktgal2.zip .\CLONES\
move spool3.zip .\CLONES\
move spool3i.zip .\CLONES\
move bldwolf.zip .\CLONES\
move actfanc1.zip .\CLONES\
move actfancj.zip .\CLONES\
move lastmsno.zip .\CLONES\
move lastmsnj.zip .\CLONES\
move breywood.zip .\CLONES\
move ghostb3.zip .\CLONES\
move meikyuh.zip .\CLONES\
move srdarwnj.zip .\CLONES\
move makyosen.zip .\CLONES\
move cobracmj.zip .\CLONES\
move oscarj.zip .\CLONES\
move oscarj1.zip .\CLONES\
move oscarj0.zip .\CLONES\
move karnovj.zip .\CLONES\
move chelnovu.zip .\CLONES\
move chelnovj.zip .\CLONES\
move hbarrelw.zip .\CLONES\
move drgninja.zip .\CLONES\
move robocopw.zip .\CLONES\
move robocopj.zip .\CLONES\
move robocopu.zip .\CLONES\
move robocpu0.zip .\CLONES\
move robocopb.zip .\CLONES\
move ffantasy.zip .\CLONES\
move ffantasa.zip .\CLONES\
move slyspy2.zip .\CLONES\
move secretag.zip .\CLONES\
move secretab.zip .\CLONES\
move midresu.zip .\CLONES\
move midresj.zip .\CLONES\
move midresbj.zip .\CLONES\
move bouldshj.zip .\CLONES\
move vaportru.zip .\CLONES\
move kuhga.zip .\CLONES\
move cbusterw.zip .\CLONES\
move cbusterj.zip .\CLONES\
move twocrude.zip .\CLONES\
move darksea1.zip .\CLONES\
move darkseaj.zip .\CLONES\
move gatedoom.zip .\CLONES\
move gatedom1.zip .\CLONES\
move edrandy1.zip .\CLONES\
move edrandyj.zip .\CLONES\
move supbtimj.zip .\CLONES\
move mutantfa.zip .\CLONES\
move deathbrd.zip .\CLONES\
move cninja0.zip .\CLONES\
move cninjau.zip .\CLONES\
move joemac.zip .\CLONES\
move stoneage.zip .\CLONES\
move robocp2u.zip .\CLONES\
move robocp2j.zip .\CLONES\
move dassault.zip .\CLONES\
move dassaul4.zip .\CLONES\
move rohgah.zip .\CLONES\
move rohgau.zip .\CLONES\
move captavna.zip .\CLONES\
move captavne.zip .\CLONES\
move captavnu.zip .\CLONES\
move captavuu.zip .\CLONES\
move captavnj.zip .\CLONES\
move tumblepj.zip .\CLONES\
move tumblepb.zip .\CLONES\
move tumblep2.zip .\CLONES\
move darksel2.zip .\CLONES\
move dietgoe.zip .\CLONES\
move dietgou.zip .\CLONES\
move dietgoj.zip .\CLONES\
move pktgaldj.zip .\CLONES\
move boogwinga.zip .\CLONES\
move ragtime.zip .\CLONES\
move ragtimea.zip .\CLONES\
move fghthistu.zip .\CLONES\
move fghthista.zip .\CLONES\
move fghthistj.zip .\CLONES\
move hvysmsha.zip .\CLONES\
move hvysmshj.zip .\CLONES\
move nslasherj.zip .\CLONES\
move nslashers.zip .\CLONES\
move joemacra.zip .\CLONES\
move tattassa.zip .\CLONES\
move sshanghb.zip .\CLONES\
move wcvol95x.zip .\CLONES\
move candance.zip .\CLONES\
move magdrop.zip .\CLONES\
move magdropp.zip .\CLONES\
move gangonta.zip .\CLONES\
move avengrgsj.zip .\CLONES\
move skullfngj.zip .\CLONES\
move ddream95.zip .\CLONES\
move starfore.zip .\CLONES\
move megaforc.zip .\CLONES\
move bombjac2.zip .\CLONES\
move pbactio2.zip .\CLONES\
move rygar2.zip .\CLONES\
move rygarj.zip .\CLONES\
move silkwrm2.zip .\CLONES\
move tbowlj.zip .\CLONES\
move shadowwa.zip .\CLONES\
move gaiden.zip .\CLONES\
move ryukendn.zip .\CLONES\
move tknight.zip .\CLONES\
move raiga.zip .\CLONES\
move wc90a.zip .\CLONES\
move wc90t.zip .\CLONES\
move wc90b.zip .\CLONES\
move spbactnj.zip .\CLONES\
move tutankst.zip .\CLONES\
move junofstg.zip .\CLONES\
move pooyans.zip .\CLONES\
move pootan.zip .\CLONES\
move timepltc.zip .\CLONES\
move spaceplt.zip .\CLONES\
move megaznik.zip .\CLONES\
move gyrussce.zip .\CLONES\
move venus.zip .\CLONES\
move trackflc.zip .\CLONES\
move hyprolym.zip .\CLONES\
move hyprolyb.zip .\CLONES\
move rocnropk.zip .\CLONES\
move circusc2.zip .\CLONES\
move circuscc.zip .\CLONES\
move circusce.zip .\CLONES\
move tp84a.zip .\CLONES\
move hpolym84.zip .\CLONES\
move sbasketo.zip .\CLONES\
move sbasketu.zip .\CLONES\
move mikiej.zip .\CLONES\
move mikiehs.zip .\CLONES\
move roadf2.zip .\CLONES\
move yiear2.zip .\CLONES\
move shaolins.zip .\CLONES\
move rushatck.zip .\CLONES\
move gberetb.zip .\CLONES\
move manhatan.zip .\CLONES\
move finalizb.zip .\CLONES\
move dairesya.zip .\CLONES\
move farwest.zip .\CLONES\
move topgunr.zip .\CLONES\
move jackalj.zip .\CLONES\
move topgunbl.zip .\CLONES\
move contrab.zip .\CLONES\
move contraj.zip .\CLONES\
move contrajb.zip .\CLONES\
move gryzor.zip .\CLONES\
move combasct.zip .\CLONES\
move combascj.zip .\CLONES\
move bootcamp.zip .\CLONES\
move combascb.zip .\CLONES\
move rockragj.zip .\CLONES\
move flkatck.zip .\CLONES\
move labyrunr.zip .\CLONES\
move labyrunk.zip .\CLONES\
move thehustj.zip .\CLONES\
move rackemup.zip .\CLONES\
move battlntj.zip .\CLONES\
move bladstle.zip .\CLONES\
move hcastleo.zip .\CLONES\
move hcastlej.zip .\CLONES\
move hcastljo.zip .\CLONES\
move typhoon.zip .\CLONES\
move ajaxj.zip .\CLONES\
move scontraj.zip .\CLONES\
move thnderxj.zip .\CLONES\
move mainevto.zip .\CLONES\
move mainev2p.zip .\CLONES\
move ringohja.zip .\CLONES\
move devstor2.zip .\CLONES\
move devstor3.zip .\CLONES\
move garuka.zip .\CLONES\
move konami88.zip .\CLONES\
move hypsptsp.zip .\CLONES\
move crazycop.zip .\CLONES\
move crimfgt2.zip .\CLONES\
move crimfgtj.zip .\CLONES\
move spyu.zip .\CLONES\
move bottom9n.zip .\CLONES\
move mstadium.zip .\CLONES\
move quarth.zip .\CLONES\
move aliens2.zip .\CLONES\
move aliensu.zip .\CLONES\
move aliensj.zip .\CLONES\
move parodisj.zip .\CLONES\
move rollergj.zip .\CLONES\
move simpsn2p.zip .\CLONES\
move simps2pa.zip .\CLONES\
move simps2pj.zip .\CLONES\
move esckidsj.zip .\CLONES\
move vendetao.zip .\CLONES\
move vendet2p.zip .\CLONES\
move vendetas.zip .\CLONES\
move vendtaso.zip .\CLONES\
move vendettj.zip .\CLONES\
move chqflagj.zip .\CLONES\
move nemesuk.zip .\CLONES\
move salamanj.zip .\CLONES\
move lifefrce.zip .\CLONES\
move lifefrcj.zip .\CLONES\
move citybmrj.zip .\CLONES\
move nyanpani.zip .\CLONES\
move hcrashc.zip .\CLONES\
move rf2.zip .\CLONES\
move gradius.zip .\CLONES\
move darkadv.zip .\CLONES\
move majuu.zip .\CLONES\
move gradius2.zip .\CLONES\
move grdius2a.zip .\CLONES\
move grdius2b.zip .\CLONES\
move froundl.zip .\CLONES\
move hpuncher.zip .\CLONES\
move miaj.zip .\CLONES\
move cuebrckj.zip .\CLONES\
move mia2.zip .\CLONES\
move tmntu.zip .\CLONES\
move tmht.zip .\CLONES\
move tmntj.zip .\CLONES\
move tmht2p.zip .\CLONES\
move tmnt2pj.zip .\CLONES\
move tmnt2po.zip .\CLONES\
move punksht2.zip .\CLONES\
move punkshtj.zip .\CLONES\
move trigon.zip .\CLONES\
move detatwin.zip .\CLONES\
move glfgretj.zip .\CLONES\
move tmnt22p.zip .\CLONES\
move tmnt2a.zip .\CLONES\
move ssrdrebd.zip .\CLONES\
move ssrdrebc.zip .\CLONES\
move ssrdruda.zip .\CLONES\
move ssrdruac.zip .\CLONES\
move ssrdrubc.zip .\CLONES\
move ssrdrabd.zip .\CLONES\
move ssrdrjbd.zip .\CLONES\
move sunsetbl.zip .\CLONES\
move xmen2p.zip .\CLONES\
move xmen2pj.zip .\CLONES\
move xmen6p.zip .\CLONES\
move xexexj.zip .\CLONES\
move astrxeac.zip .\CLONES\
move astrxeaa.zip .\CLONES\
move gijoeu.zip .\CLONES\
move gijoej.zip .\CLONES\
move thndrx2a.zip .\CLONES\
move prmrsocj.zip .\CLONES\
move mooua.zip .\CLONES\
move moobl.zip .\CLONES\
move buckyua.zip .\CLONES\
move mystwaru.zip .\CLONES\
move viostrmu.zip .\CLONES\
move viostrmj.zip .\CLONES\
move viostrma.zip .\CLONES\
move metamrpj.zip .\CLONES\
move mtlchmpj.zip .\CLONES\
move rungunu.zip .\CLONES\
move slmdunkj.zip .\CLONES\
move sbishik.zip .\CLONES\
move grdius3a.zip .\CLONES\
move grdius3e.zip .\CLONES\
move ggreats2.zip .\CLONES\
move le2u.zip .\CLONES\
move fantjour.zip .\CLONES\
move slamdnk2.zip .\CLONES\
move bm2ndmxa.zip .\CLONES\
move hmcompmx.zip .\CLONES\
move targc.zip .\CLONES\
move spectar1.zip .\CLONES\
move rallys.zip .\CLONES\
move phantoma.zip .\CLONES\
move venture2.zip .\CLONES\
move venture4.zip .\CLONES\
move mtrap3.zip .\CLONES\
move mtrap4.zip .\CLONES\
move starfira.zip .\CLONES\
move victorba.zip .\CLONES\
move catch22.zip .\CLONES\
move hitnmis2.zip .\CLONES\
move sprint2.zip .\CLONES\
move sprint2a.zip .\CLONES\
move sprint4a.zip .\CLONES\
move sprint8a.zip .\CLONES\
move starshpp.zip .\CLONES\
move canyonp.zip .\CLONES\
move tourtab2.zip .\CLONES\
move atarifb1.zip .\CLONES\
move atarifb4.zip .\CLONES\
move abaseb2.zip .\CLONES\
move missile2.zip .\CLONES\
move suprmatk.zip .\CLONES\
move llander1.zip .\CLONES\
move asteroi1.zip .\CLONES\
move asteroib.zip .\CLONES\
move asterock.zip .\CLONES\
move astdelu1.zip .\CLONES\
move bzone2.zip .\CLONES\
move bzonec.zip .\CLONES\
move tempest1.zip .\CLONES\
move tempest2.zip .\CLONES\
move tempest3.zip .\CLONES\
move temptube.zip .\CLONES\
move gravitr2.zip .\CLONES\
move gravp.zip .\CLONES\
move lunarbat.zip .\CLONES\
move lunarba1.zip .\CLONES\
move quantum1.zip .\CLONES\
move quantump.zip .\CLONES\
move starwar1.zip .\CLONES\
move mhavoc2.zip .\CLONES\
move mhavocp.zip .\CLONES\
move mhavocrv.zip .\CLONES\
move alphaone.zip .\CLONES\
move alphaona.zip .\CLONES\
move centipd2.zip .\CLONES\
move centtime.zip .\CLONES\
move centipdb.zip .\CLONES\
move centipb2.zip .\CLONES\
move millpac.zip .\CLONES\
move magworm.zip .\CLONES\
move tunhuntc.zip .\CLONES\
move liberat2.zip .\CLONES\
move foodf2.zip .\CLONES\
move foodfc.zip .\CLONES\
move ccastle3.zip .\CLONES\
move ccastle2.zip .\CLONES\
move ccastlej.zip .\CLONES\
move cloaksp.zip .\CLONES\
move cloakfr.zip .\CLONES\
move cloakgr.zip .\CLONES\
move marble2.zip .\CLONES\
move marble3.zip .\CLONES\
move marble4.zip .\CLONES\
move indytem2.zip .\CLONES\
move indytem3.zip .\CLONES\
move indytem4.zip .\CLONES\
move indytemd.zip .\CLONES\
move roadrun2.zip .\CLONES\
move roadrun1.zip .\CLONES\
move roadblsg.zip .\CLONES\
move roadbls3.zip .\CLONES\
move roadblg2.zip .\CLONES\
move roadbls2.zip .\CLONES\
move roadblg1.zip .\CLONES\
move roadbls1.zip .\CLONES\
move roadblsc.zip .\CLONES\
move roadblcg.zip .\CLONES\
move roadblc1.zip .\CLONES\
move paperbr2.zip .\CLONES\
move paperbr1.zip .\CLONES\
move ssprint3.zip .\CLONES\
move ssprint1.zip .\CLONES\
move ssprintg.zip .\CLONES\
move sspring1.zip .\CLONES\
move ssprintf.zip .\CLONES\
move ssprints.zip .\CLONES\
move csprint2.zip .\CLONES\
move csprint1.zip .\CLONES\
move csprintg.zip .\CLONES\
move cspring1.zip .\CLONES\
move csprintf.zip .\CLONES\
move csprints.zip .\CLONES\
move csprins1.zip .\CLONES\
move 720r3.zip .\CLONES\
move 720r2.zip .\CLONES\
move 720r1.zip .\CLONES\
move 720g.zip .\CLONES\
move 720gr1.zip .\CLONES\
move apb6.zip .\CLONES\
move apb5.zip .\CLONES\
move apb4.zip .\CLONES\
move apb3.zip .\CLONES\
move apb2.zip .\CLONES\
move apb1.zip .\CLONES\
move apbg.zip .\CLONES\
move apbf.zip .\CLONES\
move harddrvb.zip .\CLONES\
move harddrvg.zip .\CLONES\
move harddrvj.zip .\CLONES\
move harddrb6.zip .\CLONES\
move harddrj6.zip .\CLONES\
move harddrb5.zip .\CLONES\
move harddrg4.zip .\CLONES\
move harddrv3.zip .\CLONES\
move harddrv2.zip .\CLONES\
move harddrv1.zip .\CLONES\
move harddrvc.zip .\CLONES\
move harddrcg.zip .\CLONES\
move harddrcb.zip .\CLONES\
move harddrc1.zip .\CLONES\
move stunrunj.zip .\CLONES\
move stunrun5.zip .\CLONES\
move stunrune.zip .\CLONES\
move stunrun4.zip .\CLONES\
move stunrun3.zip .\CLONES\
move stunrn3e.zip .\CLONES\
move stunrun2.zip .\CLONES\
move stunrn2e.zip .\CLONES\
move stunrun0.zip .\CLONES\
move stunrunp.zip .\CLONES\
move racedrvb.zip .\CLONES\
move racedrvg.zip .\CLONES\
move racedrv4.zip .\CLONES\
move racedrb4.zip .\CLONES\
move racedrg4.zip .\CLONES\
move racedrv3.zip .\CLONES\
move racedrv2.zip .\CLONES\
move racedrv1.zip .\CLONES\
move racedrb1.zip .\CLONES\
move racedrg1.zip .\CLONES\
move racedrvc.zip .\CLONES\
move racedrcb.zip .\CLONES\
move racedrcg.zip .\CLONES\
move racedrc4.zip .\CLONES\
move racedcb4.zip .\CLONES\
move racedcg4.zip .\CLONES\
move racedrc2.zip .\CLONES\
move racedrc1.zip .\CLONES\
move steeltag.zip .\CLONES\
move steelta1.zip .\CLONES\
move steeltap.zip .\CLONES\
move hdrivaip.zip .\CLONES\
move gaunts.zip .\CLONES\
move gauntj.zip .\CLONES\
move gauntg.zip .\CLONES\
move gauntj12.zip .\CLONES\
move gauntr9.zip .\CLONES\
move gauntgr8.zip .\CLONES\
move gauntr7.zip .\CLONES\
move gauntgr6.zip .\CLONES\
move gauntr5.zip .\CLONES\
move gauntr4.zip .\CLONES\
move gauntgr3.zip .\CLONES\
move gauntr2.zip .\CLONES\
move gauntr1.zip .\CLONES\
move gaunt2p.zip .\CLONES\
move gaunt2pj.zip .\CLONES\
move gaunt2pg.zip .\CLONES\
move gaun2pr3.zip .\CLONES\
move gaun2pj2.zip .\CLONES\
move gaun2pg1.zip .\CLONES\
move gaunt2g.zip .\CLONES\
move gaunt22p.zip .\CLONES\
move gaun22p1.zip .\CLONES\
move gaun22pg.zip .\CLONES\
move vindc2r2.zip .\CLONES\
move vindc2r1.zip .\CLONES\
move xybotsg.zip .\CLONES\
move xybotsf.zip .\CLONES\
move xybots1.zip .\CLONES\
move xybots0.zip .\CLONES\
move blstroi3.zip .\CLONES\
move blstroi2.zip .\CLONES\
move blstroig.zip .\CLONES\
move blsthead.zip .\CLONES\
move vindicte.zip .\CLONES\
move vindictg.zip .\CLONES\
move vindice4.zip .\CLONES\
move vindict4.zip .\CLONES\
move vindice3.zip .\CLONES\
move vindict2.zip .\CLONES\
move vindict1.zip .\CLONES\
move toobine.zip .\CLONES\
move toobing.zip .\CLONES\
move toobin2.zip .\CLONES\
move toobin2e.zip .\CLONES\
move toobin1.zip .\CLONES\
move cyberba2.zip .\CLONES\
move cyberbap.zip .\CLONES\
move atetcktl.zip .\CLONES\
move atetckt2.zip .\CLONES\
move atetrisa.zip .\CLONES\
move atetrisb.zip .\CLONES\
move eprom2.zip .\CLONES\
move skullxb4.zip .\CLONES\
move skullxb3.zip .\CLONES\
move skullxb2.zip .\CLONES\
move skullxb1.zip .\CLONES\
move cyberbt.zip .\CLONES\
move cyberbt1.zip .\CLONES\
move klax2.zip .\CLONES\
move klax3.zip .\CLONES\
move klaxj.zip .\CLONES\
move klaxd.zip .\CLONES\
move klaxp1.zip .\CLONES\
move klaxp2.zip .\CLONES\
move cyberb2p.zip .\CLONES\
move cyberb23.zip .\CLONES\
move cyberb22.zip .\CLONES\
move cyberb21.zip .\CLONES\
move hydrap.zip .\CLONES\
move hydrap2.zip .\CLONES\
move pitfigh3.zip .\CLONES\
move pitfighj.zip .\CLONES\
move pitfighb.zip .\CLONES\
move ramprt2p.zip .\CLONES\
move rampartj.zip .\CLONES\
move shuuz2.zip .\CLONES\
move offtwalc.zip .\CLONES\
move relief2.zip .\CLONES\
move spclorda.zip .\CLONES\
move rrrevenp.zip .\CLONES\
move tmekprot.zip .\CLONES\
move primraga.zip .\CLONES\
move a51mxr3k.zip .\CLONES\
move maxf_102.zip .\CLONES\
move zarzon.zip .\CLONES\
move vangrdce.zip .\CLONES\
move fantasyj.zip .\CLONES\
move nibblera.zip .\CLONES\
move pinbos.zip .\CLONES\
move mnchmobl.zip .\CLONES\
move hal21j.zip .\CLONES\
move tnk3j.zip .\CLONES\
move fitegol2.zip .\CLONES\
move countryc.zip .\CLONES\
move ikarijp.zip .\CLONES\
move ikarijpb.zip .\CLONES\
move dogosoke.zip .\CLONES\
move dogosokj.zip .\CLONES\
move gwarj.zip .\CLONES\
move gwara.zip .\CLONES\
move gwarb.zip .\CLONES\
move bermudao.zip .\CLONES\
move bermudaa.zip .\CLONES\
move worldwar.zip .\CLONES\
move psychosj.zip .\CLONES\
move choppera.zip .\CLONES\
move chopperb.zip .\CLONES\
move legofair.zip .\CLONES\
move tdfeverj.zip .\CLONES\
move tdfever2.zip .\CLONES\
move ikari3nr.zip .\CLONES\
move powj.zip .\CLONES\
move sercharu.zip .\CLONES\
move streets1.zip .\CLONES\
move streetsw.zip .\CLONES\
move streetsj.zip .\CLONES\
move prehislu.zip .\CLONES\
move gensitou.zip .\CLONES\
move shougi2.zip .\CLONES\
move champbbj.zip .\CLONES\
move champbja.zip .\CLONES\
move exctscca.zip .\CLONES\
move exctsccb.zip .\CLONES\
move exctscc2.zip .\CLONES\
move equitess.zip .\CLONES\
move kyrosj.zip .\CLONES\
move timesol1.zip .\CLONES\
move btlfield.zip .\CLONES\
move goldmedb.zip .\CLONES\
move skyadvnu.zip .\CLONES\
move skyadvnj.zip .\CLONES\
move gangwarb.zip .\CLONES\
move eggs.zip .\CLONES\
move tagteam.zip .\CLONES\
move myststno.zip .\CLONES\
move dogfgtj.zip .\CLONES\
move excthour.zip .\CLONES\
move maniach2.zip .\CLONES\
move kuniokun.zip .\CLONES\
move kuniokub.zip .\CLONES\
move xsleenab.zip .\CLONES\
move solarwar.zip .\CLONES\
move battlan2.zip .\CLONES\
move battlan3.zip .\CLONES\
move ddragonu.zip .\CLONES\
move ddragonw.zip .\CLONES\
move ddragonb.zip .\CLONES\
move nkdodgeb.zip .\CLONES\
move saiyugou.zip .\CLONES\
move saiyugb1.zip .\CLONES\
move saiyugb2.zip .\CLONES\
move vball2pj.zip .\CLONES\
move ddragn2u.zip .\CLONES\
move ctribeb.zip .\CLONES\
move blckout2.zip .\CLONES\
move blckoutj.zip .\CLONES\
move ddragon3j.zip .\CLONES\
move ddrago3b.zip .\CLONES\
move wwfwfsta.zip .\CLONES\
move wwfwfstj.zip .\CLONES\
move berzerk1.zip .\CLONES\
move tinv2650.zip .\CLONES\
move jackrab2.zip .\CLONES\
move jackrabs.zip .\CLONES\
move mouserc.zip .\CLONES\
move nov2001u.zip .\CLONES\
move raidrs5t.zip .\CLONES\
move pkunwarj.zip .\CLONES\
move ninjak2a.zip .\CLONES\
move ninjak2b.zip .\CLONES\
move rdaction.zip .\CLONES\
move robokidj.zip .\CLONES\
move omegafs.zip .\CLONES\
move tharierj.zip .\CLONES\
move mustangs.zip .\CLONES\
move mustangb.zip .\CLONES\
move vandyjal.zip .\CLONES\
move blkhearj.zip .\CLONES\
move strahla.zip .\CLONES\
move bigbang.zip .\CLONES\
move tdragonb.zip .\CLONES\
move hachamfb.zip .\CLONES\
move sabotnba.zip .\CLONES\
move airattcka.zip .\CLONES\
move narc3.zip .\CLONES\
move trog3.zip .\CLONES\
move trogpa6.zip .\CLONES\
move trogp.zip .\CLONES\
move smashtv6.zip .\CLONES\
move smashtv5.zip .\CLONES\
move smashtv4.zip .\CLONES\
move shimpacp.zip .\CLONES\
move mkr4.zip .\CLONES\
move mkprot9.zip .\CLONES\
move mkla1.zip .\CLONES\
move mkla2.zip .\CLONES\
move mkla3.zip .\CLONES\
move mkla4.zip .\CLONES\
move term2la2.zip .\CLONES\
move term2la1.zip .\CLONES\
move totcarnp.zip .\CLONES\
move mk2r32.zip .\CLONES\
move mk2r21.zip .\CLONES\
move mk2r14.zip .\CLONES\
move mk2r42.zip .\CLONES\
move mk2r91.zip .\CLONES\
move mk2chal.zip .\CLONES\
move nbajamr2.zip .\CLONES\
move nbajamte.zip .\CLONES\
move nbajamt1.zip .\CLONES\
move nbajamt2.zip .\CLONES\
move nbajamt3.zip .\CLONES\
move mk3r20.zip .\CLONES\
move mk3r10.zip .\CLONES\
move umk3.zip .\CLONES\
move umk3r11.zip .\CLONES\
move nbamaxht.zip .\CLONES\
move rmpgwt11.zip .\CLONES\
move crusnu40.zip .\CLONES\
move crusnu21.zip .\CLONES\
move crusnw20.zip .\CLONES\
move crusnw13.zip .\CLONES\
move tripoola.zip .\CLONES\
move jack2.zip .\CLONES\
move jack3.zip .\CLONES\
move treahunt.zip .\CLONES\
move zzyzzyx2.zip .\CLONES\
move brix.zip .\CLONES\
move starcas1.zip .\CLONES\
move starcasp.zip .\CLONES\
move starcase.zip .\CLONES\
move stellcas.zip .\CLONES\
move armorap.zip .\CLONES\
move armorar.zip .\CLONES\
move cchasm1.zip .\CLONES\
move fitter.zip .\CLONES\
move portman.zip .\CLONES\
move suprmous.zip .\CLONES\
move intrepi2.zip .\CLONES\
move bagnard.zip .\CLONES\
move bagmans.zip .\CLONES\
move bagmans2.zip .\CLONES\
move sbagmans.zip .\CLONES\
move stinger2.zip .\CLONES\
move scionc.zip .\CLONES\
move wizt.zip .\CLONES\
move kncljoea.zip .\CLONES\
move bcrusher.zip .\CLONES\
move empcityj.zip .\CLONES\
move stfight.zip .\CLONES\
move cshootre.zip .\CLONES\
move airraid.zip .\CLONES\
move ghunter.zip .\CLONES\
move dbldyn.zip .\CLONES\
move raidena.zip .\CLONES\
move raidenk.zip .\CLONES\
move raident.zip .\CLONES\
move cabala.zip .\CLONES\
move cabalus.zip .\CLONES\
move cabalus2.zip .\CLONES\
move cabalbl.zip .\CLONES\
move tokia.zip .\CLONES\
move tokij.zip .\CLONES\
move tokiu.zip .\CLONES\
move tokib.zip .\CLONES\
move weststry.zip .\CLONES\
move legionnu.zip .\CLONES\
move heatbrlo.zip .\CLONES\
move heatbrlu.zip .\CLONES\
move cupsoc2.zip .\CLONES\
move olysoc92.zip .\CLONES\
move cupsocbl.zip .\CLONES\
move goal92.zip .\CLONES\
move exeriont.zip .\CLONES\
move exerionb.zip .\CLONES\
move aeroboto.zip .\CLONES\
move citycona.zip .\CLONES\
move cruisin.zip .\CLONES\
move exerizrb.zip .\CLONES\
move teplus2j.zip .\CLONES\
move rockna.zip .\CLONES\
move makaiden.zip .\CLONES\
move p47j.zip .\CLONES\
move tshingna.zip .\CLONES\
move lordofk.zip .\CLONES\
move rodlandj.zip .\CLONES\
move rodlndjb.zip .\CLONES\
move phantasm.zip .\CLONES\
move 64streej.zip .\CLONES\
move bigstrkb.zip .\CLONES\
move 47pie2o.zip .\CLONES\
move gratiaa.zip .\CLONES\
move tp2m32.zip .\CLONES\
move rpunch.zip .\CLONES\
move svolleyk.zip .\CLONES\
move svolleyu.zip .\CLONES\
move sformula.zip .\CLONES\
move natsuiro.zip .\CLONES\
move pipedrmj.zip .\CLONES\
move spinlbru.zip .\CLONES\
move spinlbrj.zip .\CLONES\
move pspikesk.zip .\CLONES\
move svolly91.zip .\CLONES\
move karatblu.zip .\CLONES\
move aerofgtb.zip .\CLONES\
move aerofgtc.zip .\CLONES\
move sonicwi.zip .\CLONES\
move crshrac2.zip .\CLONES\
move taotaida.zip .\CLONES\
move vgoalsca.zip .\CLONES\
move sngkace.zip .\CLONES\
move gunbirdk.zip .\CLONES\
move gunbirdj.zip .\CLONES\
move s1945j.zip .\CLONES\
move s1945jn.zip .\CLONES\
move loderdfa.zip .\CLONES\
move tgm2p.zip .\CLONES\
move looper.zip .\CLONES\
move hoccer2.zip .\CLONES\
move espiale.zip .\CLONES\
move vastar2.zip .\CLONES\
move wrallya.zip .\CLONES\
move glasskr.zip .\CLONES\
move aligatun.zip .\CLONES\
move maniacsp.zip .\CLONES\
move snowbalt.zip .\CLONES\
move bangj.zip .\CLONES\
move airbustj.zip .\CLONES\
move galpanib.zip .\CLONES\
move berlwalt.zip .\CLONES\
move mgcrystj.zip .\CLONES\
move fjbuster.zip .\CLONES\
move brapboysj.zip .\CLONES\
move gtmre.zip .\CLONES\
move gtmrusa.zip .\CLONES\
move sengekij.zip .\CLONES\
move sarukani.zip .\CLONES\
move puzloopj.zip .\CLONES\
move puzloopu.zip .\CLONES\
move mjyuugia.zip .\CLONES\
move ponchina.zip .\CLONES\
move tndrcadj.zip .\CLONES\
move downtowj.zip .\CLONES\
move blandiap.zip .\CLONES\
move msgunda1.zip .\CLONES\
move triplfun.zip .\CLONES\
move deerhunta.zip .\CLONES\
move deerhuntb.zip .\CLONES\
move wschampa.zip .\CLONES\
move srmp4o.zip .\CLONES\
move eaglshta.zip .\CLONES\
move vasara2a.zip .\CLONES\
move powerina.zip .\CLONES\
move blmbycau.zip .\CLONES\
move stratvox.zip .\CLONES\
move spacecho.zip .\CLONES\
move route16a.zip .\CLONES\
move route16b.zip .\CLONES\
move routex.zip .\CLONES\
move kangaroa.zip .\CLONES\
move kangarob.zip .\CLONES\
move arabiana.zip .\CLONES\
move guiness.zip .\CLONES\
move goindolu.zip .\CLONES\
move goindolj.zip .\CLONES\
move sranger.zip .\CLONES\
move srangerb.zip .\CLONES\
move srangerw.zip .\CLONES\
move hardhedb.zip .\CLONES\
move brickzn3.zip .\CLONES\
move gundeala.zip .\CLONES\
move gundealt.zip .\CLONES\
move wiseguy.zip .\CLONES\
move lastdaya.zip .\CLONES\
move gulfstr2.zip .\CLONES\
move polluxa.zip .\CLONES\
move bluehawn.zip .\CLONES\
move primella.zip .\CLONES\
move superxm.zip .\CLONES\
move potogold.zip .\CLONES\
move beezer1.zip .\CLONES\
move natodefa.zip .\CLONES\
move moegonta.zip .\CLONES\
move pangpomm.zip .\CLONES\
move lastfero.zip .\CLONES\
move hyprdelj.zip .\CLONES\
move spcforc2.zip .\CLONES\
move meteor.zip .\CLONES\
move loopinga.zip .\CLONES\
move blueprnj.zip .\CLONES\
move gogomilj.zip .\CLONES\
move zeropnta.zip .\CLONES\
move redhawk.zip .\CLONES\
move multchmpk.zip .\CLONES\
move hedpanicf.zip .\CLONES\
move hedpanico.zip .\CLONES\
move mchampdxa.zip .\CLONES\
move hnfubuki.zip .\CLONES\
move hnkochou.zip .\CLONES\
move sprtmtch.zip .\CLONES\
move roldfrga.zip .\CLONES\
move quizchql.zip .\CLONES\
move nynyg.zip .\CLONES\
move arcadia.zip .\CLONES\
move spiders2.zip .\CLONES\
move vbowlj.zip .\CLONES\
move orlegnde.zip .\CLONES\
move orlegndc.zip .\CLONES\
move olds103t.zip .\CLONES\
move kovplus.zip .\CLONES\
move kov115.zip .\CLONES\
move kovsh.zip .\CLONES\
move mblkjack.zip .\CLONES\
move brickyrd.zip .\CLONES\
move usg82.zip .\CLONES\
move usg83x.zip .\CLONES\
move oigas.zip .\CLONES\
move pbillrds.zip .\CLONES\
move freekckb.zip .\CLONES\
move countrnb.zip .\CLONES\
move countrb2.zip .\CLONES\
move rmhaihib.zip .\CLONES\
move stoneba2.zip .\CLONES\
move chinher2.zip .\CLONES\
move hiryuken.zip .\CLONES\
move kamikaze.zip .\CLONES\
move spacefbg.zip .\CLONES\
move spacefbb.zip .\CLONES\
move spacebrd.zip .\CLONES\
move spacedem.zip .\CLONES\
move deltrace.zip .\CLONES\
move ddayc.zip .\CLONES\
move ringking.zip .\CLONES\
move ringkin2.zip .\CLONES\
move ringkin3.zip .\CLONES\
move ambusht.zip .\CLONES\
move homo.zip .\CLONES\
move gotya.zip .\CLONES\
move crazyblk.zip .\CLONES\
move blkbustr.zip .\CLONES\
move amspdwya.zip .\CLONES\
move mosaica.zip .\CLONES\
move policeto.zip .\CLONES\
move plctr13b.zip .\CLONES\
move driblino.zip .\CLONES\
move mcatadvj.zip .\CLONES\
move nostj.zip .\CLONES\
move nostk.zip .\CLONES\
move maddonnb.zip .\CLONES\
move 9ballsht.zip .\CLONES\
move 9ballsh2.zip .\CLONES\
move 9ballsh3.zip .\CLONES\
move crgolfa.zip .\CLONES\
move crgolfb.zip .\CLONES\
move crgolfc.zip .\CLONES\
move rundeep.zip .\CLONES\
move eggvntdx.zip .\CLONES\
move enigma2a.zip .\CLONES\
move maglordh.zip .\CLONES\
move ridheroh.zip .\CLONES\
move kotmh.zip .\CLONES\
move sengokh.zip .\CLONES\
move burningh.zip .\CLONES\
move 2020bbh.zip .\CLONES\
move wh1h.zip .\CLONES\
move fatfursa.zip .\CLONES\
move fightfva.zip .\CLONES\
move pbobblna.zip .\CLONES\
move kof95a.zip .\CLONES\
move kof96h.zip .\CLONES\
move kof97a.zip .\CLONES\
move lastblda.zip .\CLONES\
move puzzldpr.zip .\CLONES\
move shocktra.zip .\CLONES\
move rbff2a.zip .\CLONES\
move kof98n.zip .\CLONES\
move breakrev.zip .\CLONES\
move kof99a.zip .\CLONES\
move kof99e.zip .\CLONES\
move kof99n.zip .\CLONES\
move kof99p.zip .\CLONES\
move garouo.zip .\CLONES\
move garoup.zip .\CLONES\
move mslug3n.zip .\CLONES\
move kof2000n.zip .\CLONES\
move kof10th.zip .\CLONES\
move keta.zip .\CLONES\
move ketb.zip .\CLONES\
move ddp3a.zip .\CLONES\
move ddp3b.zip .\CLONES\
move ddp3blk.zip .\CLONES\
