md FIGHTERVS
move aodk.zip .\FIGHTERVS\
move aof2.zip .\FIGHTERVS\
move aof3.zip .\FIGHTERVS\
move aof.zip .\FIGHTERVS\
move asurabld.zip .\FIGHTERVS\
move asurabus.zip .\FIGHTERVS\
move avengrgs.zip .\FIGHTERVS\
move avengrgsj.zip .\FIGHTERVS\
move bbprot.zip .\FIGHTERVS\
move biofreak.zip .\FIGHTERVS\
move bloods11.zip .\FIGHTERVS\
move bloods21.zip .\FIGHTERVS\
move bloods22.zip .\FIGHTERVS\
move bloodstm.zip .\FIGHTERVS\
move bloodwar.zip .\FIGHTERVS\
move boxer.zip .\FIGHTERVS\
move breakers.zip .\FIGHTERVS\
move breakrev.zip .\FIGHTERVS\
move brival.zip .\FIGHTERVS\
move btlkroad.zip .\FIGHTERVS\
move cutefght.zip .\FIGHTERVS\
move cybots.zip .\FIGHTERVS\
move cybotsj.zip .\FIGHTERVS\
move dankuga.zip .\FIGHTERVS\
move daraku.zip .\FIGHTERVS\
move dbz2.zip .\FIGHTERVS\
move dbz.zip .\FIGHTERVS\
move deathbrd.zip .\FIGHTERVS\
move dinorex.zip .\FIGHTERVS\
move dinorexj.zip .\FIGHTERVS\
move dinorexu.zip .\FIGHTERVS\
move doubledr.zip .\FIGHTERVS\
move dragoonj.zip .\FIGHTERVS\
move drgnmst.zip .\FIGHTERVS\
move dstlk.zip .\FIGHTERVS\
move dstlka.zip .\FIGHTERVS\
move dstlku.zip .\FIGHTERVS\
move dstlkur1.zip .\FIGHTERVS\
move ehrgeiz.zip .\FIGHTERVS\
move fatfursa.zip .\FIGHTERVS\
move fatfursp.zip .\FIGHTERVS\
move fatfury1.zip .\FIGHTERVS\
move fatfury2.zip .\FIGHTERVS\
move fatfury3.zip .\FIGHTERVS\
move ffantasa.zip .\FIGHTERVS\
move ffantasy.zip .\FIGHTERVS\
move fghthist.zip .\FIGHTERVS\
move fghthista.zip .\FIGHTERVS\
move fghthistj.zip .\FIGHTERVS\
move fghthistu.zip .\FIGHTERVS\
move fgtlayer.zip .\FIGHTERVS\
move fightfev.zip .\FIGHTERVS\
move fightfva.zip .\FIGHTERVS\
move fitfight.zip .\FIGHTERVS\
move gaia.zip .\FIGHTERVS\
move galaxyfg.zip .\FIGHTERVS\
move garou.zip .\FIGHTERVS\
move garouo.zip .\FIGHTERVS\
move garoup.zip .\FIGHTERVS\
move gblchmp.zip .\FIGHTERVS\
move gowcaizr.zip .\FIGHTERVS\
move gundamex.zip .\FIGHTERVS\
move gwarrior.zip .\FIGHTERVS\
move hippodrm.zip .\FIGHTERVS\
move hiryuken.zip .\FIGHTERVS\
move histryma.zip .\FIGHTERVS\
move holo.zip .\FIGHTERVS\
move hsf2a.zip .\FIGHTERVS\
move kabukikl.zip .\FIGHTERVS\
move kageki.zip .\FIGHTERVS\
move kagekij.zip .\FIGHTERVS\
move kaiserkj.zip .\FIGHTERVS\
move kaiserkn.zip .\FIGHTERVS\
move karatedo.zip .\FIGHTERVS\
move karatevs.zip .\FIGHTERVS\
move karatour.zip .\FIGHTERVS\
move karnovr.zip .\FIGHTERVS\
move kchamp.zip .\FIGHTERVS\
move kchampvs.zip .\FIGHTERVS\
move killbld.zip .\FIGHTERVS\
move kinst2.zip .\FIGHTERVS\
move kinst.zip .\FIGHTERVS\
move kizuna.zip .\FIGHTERVS\
move knckhead.zip .\FIGHTERVS\
move knckhedj.zip .\FIGHTERVS\
move kof10th.zip .\FIGHTERVS\
move kof2000.zip .\FIGHTERVS\
move kof2000n.zip .\FIGHTERVS\
move kof2001.zip .\FIGHTERVS\
move kof2002.zip .\FIGHTERVS\
move kof2003d.zip .\FIGHTERVS\
move kof94.zip .\FIGHTERVS\
move kof95.zip .\FIGHTERVS\
move kof95a.zip .\FIGHTERVS\
move kof96.zip .\FIGHTERVS\
move kof96h.zip .\FIGHTERVS\
move kof97.zip .\FIGHTERVS\
move kof97a.zip .\FIGHTERVS\
move kof98.zip .\FIGHTERVS\
move kof98n.zip .\FIGHTERVS\
move kof99.zip .\FIGHTERVS\
move kof99a.zip .\FIGHTERVS\
move kof99e.zip .\FIGHTERVS\
move kof99n.zip .\FIGHTERVS\
move kof99p.zip .\FIGHTERVS\
move kotm.zip .\FIGHTERVS\
move kotmh.zip .\FIGHTERVS\
move lastblad.zip .\FIGHTERVS\
move lastbld2.zip .\FIGHTERVS\
move lastblda.zip .\FIGHTERVS\
move legendos.zip .\FIGHTERVS\
move mace.zip .\FIGHTERVS\
move matrim.zip .\FIGHTERVS\
move mk2.zip .\FIGHTERVS\
move mk2chal.zip .\FIGHTERVS\
move mk2r14.zip .\FIGHTERVS\
move mk2r21.zip .\FIGHTERVS\
move mk2r32.zip .\FIGHTERVS\
move mk2r42.zip .\FIGHTERVS\
move mk2r91.zip .\FIGHTERVS\
move mk3.zip .\FIGHTERVS\
move mk3r10.zip .\FIGHTERVS\
move mk3r20.zip .\FIGHTERVS\
move mk.zip .\FIGHTERVS\
move mkla1.zip .\FIGHTERVS\
move mkla2.zip .\FIGHTERVS\
move mkla3.zip .\FIGHTERVS\
move mkla4.zip .\FIGHTERVS\
move mkprot9.zip .\FIGHTERVS\
move mkr4.zip .\FIGHTERVS\
move msgunda1.zip .\FIGHTERVS\
move msgundam.zip .\FIGHTERVS\
move msha.zip .\FIGHTERVS\
move mshh.zip .\FIGHTERVS\
move mshj.zip .\FIGHTERVS\
move mshu.zip .\FIGHTERVS\
move mshvsf.zip .\FIGHTERVS\
move mshvsfa1.zip .\FIGHTERVS\
move mshvsfa.zip .\FIGHTERVS\
move mshvsfb1.zip .\FIGHTERVS\
move mshvsfb.zip .\FIGHTERVS\
move mshvsfh.zip .\FIGHTERVS\
move mshvsfj1.zip .\FIGHTERVS\
move mshvsfj2.zip .\FIGHTERVS\
move mshvsfj.zip .\FIGHTERVS\
move mshvsfu1.zip .\FIGHTERVS\
move mtlchamp.zip .\FIGHTERVS\
move mtlchmpj.zip .\FIGHTERVS\
move mutantf.zip .\FIGHTERVS\
move mutantfa.zip .\FIGHTERVS\
move mvsc.zip .\FIGHTERVS\
move mvsca.zip .\FIGHTERVS\
move mvsch.zip .\FIGHTERVS\
move mvscj.zip .\FIGHTERVS\
move mvscjr1.zip .\FIGHTERVS\
move mwarr.zip .\FIGHTERVS\
move ninjamas.zip .\FIGHTERVS\
move nwarr.zip .\FIGHTERVS\
move nwarrb.zip .\FIGHTERVS\
move nwarrh.zip .\FIGHTERVS\
move onna34ra.zip .\FIGHTERVS\
move onna34ro.zip .\FIGHTERVS\
move pfghtj.zip .\FIGHTERVS\
move pitfigh3.zip .\FIGHTERVS\
move pitfighb.zip .\FIGHTERVS\
move pitfighj.zip .\FIGHTERVS\
move pitfight.zip .\FIGHTERVS\
move plegends.zip .\FIGHTERVS\
move powerina.zip .\FIGHTERVS\
move powerins.zip .\FIGHTERVS\
move primraga.zip .\FIGHTERVS\
move primrage.zip .\FIGHTERVS\
move psoldier.zip .\FIGHTERVS\
move pwrinst2.zip .\FIGHTERVS\
move ragnagrd.zip .\FIGHTERVS\
move rbff1.zip .\FIGHTERVS\
move rbff2.zip .\FIGHTERVS\
move rbff2a.zip .\FIGHTERVS\
move rbffspec.zip .\FIGHTERVS\
move reikaids.zip .\FIGHTERVS\
move rotd.zip .\FIGHTERVS\
move samsh5sp.zip .\FIGHTERVS\
move samsho2.zip .\FIGHTERVS\
move samsho3.zip .\FIGHTERVS\
move samsho4.zip .\FIGHTERVS\
move samsho5.zip .\FIGHTERVS\
move samsho.zip .\FIGHTERVS\
move savagere.zip .\FIGHTERVS\
move sf1.zip .\FIGHTERVS\
move sf1jp.zip .\FIGHTERVS\
move sf1p.zip .\FIGHTERVS\
move sf1us.zip .\FIGHTERVS\
move sf2.zip .\FIGHTERVS\
move sf2accp2.zip .\FIGHTERVS\
move sf2ce.zip .\FIGHTERVS\
move sf2cej.zip .\FIGHTERVS\
move sf2ceua.zip .\FIGHTERVS\
move sf2ceub.zip .\FIGHTERVS\
move sf2ceuc.zip .\FIGHTERVS\
move sf2eb.zip .\FIGHTERVS\
move sf2j.zip .\FIGHTERVS\
move sf2ja.zip .\FIGHTERVS\
move sf2jc.zip .\FIGHTERVS\
move sf2koryu.zip .\FIGHTERVS\
move sf2m1.zip .\FIGHTERVS\
move sf2m2.zip .\FIGHTERVS\
move sf2m3.zip .\FIGHTERVS\
move sf2m4.zip .\FIGHTERVS\
move sf2m5.zip .\FIGHTERVS\
move sf2m6.zip .\FIGHTERVS\
move sf2m7.zip .\FIGHTERVS\
move sf2rb2.zip .\FIGHTERVS\
move sf2rb.zip .\FIGHTERVS\
move sf2red.zip .\FIGHTERVS\
move sf2t.zip .\FIGHTERVS\
move sf2tj.zip .\FIGHTERVS\
move sf2ua.zip .\FIGHTERVS\
move sf2ub.zip .\FIGHTERVS\
move sf2ud.zip .\FIGHTERVS\
move sf2ue.zip .\FIGHTERVS\
move sf2uf.zip .\FIGHTERVS\
move sf2ui.zip .\FIGHTERVS\
move sf2uk.zip .\FIGHTERVS\
move sf2v004.zip .\FIGHTERVS\
move sf2yyc.zip .\FIGHTERVS\
move sfa2.zip .\FIGHTERVS\
move sfa3.zip .\FIGHTERVS\
move sfa3r1.zip .\FIGHTERVS\
move sfa.zip .\FIGHTERVS\
move sfar1.zip .\FIGHTERVS\
move sfar2.zip .\FIGHTERVS\
move sfau.zip .\FIGHTERVS\
move sftm110.zip .\FIGHTERVS\
move sftm111.zip .\FIGHTERVS\
move sftm.zip .\FIGHTERVS\
move sftmj.zip .\FIGHTERVS\
move sfz2a.zip .\FIGHTERVS\
move sfz2aa.zip .\FIGHTERVS\
move sfz2ab.zip .\FIGHTERVS\
move sfz2ah.zip .\FIGHTERVS\
move sfz2aj.zip .\FIGHTERVS\
move sfz2b.zip .\FIGHTERVS\
move sfz2br1.zip .\FIGHTERVS\
move sfz2j.zip .\FIGHTERVS\
move sfz3a.zip .\FIGHTERVS\
move sfz3j.zip .\FIGHTERVS\
move sfz3jr1.zip .\FIGHTERVS\
move sfzb.zip .\FIGHTERVS\
move sfzh.zip .\FIGHTERVS\
move sfzj.zip .\FIGHTERVS\
move sfzjr1.zip .\FIGHTERVS\
move sfzjr2.zip .\FIGHTERVS\
move sgemf.zip .\FIGHTERVS\
move sgemfa.zip .\FIGHTERVS\
move sgemfh.zip .\FIGHTERVS\
move shangkid.zip .\FIGHTERVS\
move shogwarr.zip .\FIGHTERVS\
move solfigtr.zip .\FIGHTERVS\
move soulclbr.zip .\FIGHTERVS\
move souledga.zip .\FIGHTERVS\
move souledgb.zip .\FIGHTERVS\
move souledge.zip .\FIGHTERVS\
move ssf2.zip .\FIGHTERVS\
move ssf2a.zip .\FIGHTERVS\
move ssf2ar1.zip .\FIGHTERVS\
move ssf2j.zip .\FIGHTERVS\
move ssf2jr1.zip .\FIGHTERVS\
move ssf2jr2.zip .\FIGHTERVS\
move ssf2t.zip .\FIGHTERVS\
move ssf2ta.zip .\FIGHTERVS\
move ssf2tb.zip .\FIGHTERVS\
move ssf2tbj.zip .\FIGHTERVS\
move ssf2tu.zip .\FIGHTERVS\
move ssf2tur1.zip .\FIGHTERVS\
move ssf2u.zip .\FIGHTERVS\
move ssf2xj.zip .\FIGHTERVS\
move ssoldier.zip .\FIGHTERVS\
move survarts.zip .\FIGHTERVS\
move svcboot.zip .\FIGHTERVS\
move taotaida.zip .\FIGHTERVS\
move taotaido.zip .\FIGHTERVS\
move tattass.zip .\FIGHTERVS\
move tattassa.zip .\FIGHTERVS\
move tekken2.zip .\FIGHTERVS\
move tekken2a.zip .\FIGHTERVS\
move tekken2b.zip .\FIGHTERVS\
move tekken3.zip .\FIGHTERVS\
move tekken.zip .\FIGHTERVS\
move tekkena.zip .\FIGHTERVS\
move tekkenb.zip .\FIGHTERVS\
move timek131.zip .\FIGHTERVS\
move timekill.zip .\FIGHTERVS\
move tmek.zip .\FIGHTERVS\
move tmekprot.zip .\FIGHTERVS\
move ultraman.zip .\FIGHTERVS\
move umk3.zip .\FIGHTERVS\
move umk3r11.zip .\FIGHTERVS\
move vampj.zip .\FIGHTERVS\
move vampja.zip .\FIGHTERVS\
move vampjr1.zip .\FIGHTERVS\
move vcircle.zip .\FIGHTERVS\
move vf.zip .\FIGHTERVS\
move vfkids.zip .\FIGHTERVS\
move vhunt2r1.zip .\FIGHTERVS\
move vhuntj.zip .\FIGHTERVS\
move vhuntjr1.zip .\FIGHTERVS\
move viofight.zip .\FIGHTERVS\
move vsav2.zip .\FIGHTERVS\
move vsav.zip .\FIGHTERVS\
move vsava.zip .\FIGHTERVS\
move vsavh.zip .\FIGHTERVS\
move vsavj.zip .\FIGHTERVS\
move vsavu.zip .\FIGHTERVS\
move wakuwak7.zip .\FIGHTERVS\
move wargods.zip .\FIGHTERVS\
move wh1.zip .\FIGHTERVS\
move wh1h.zip .\FIGHTERVS\
move wh2.zip .\FIGHTERVS\
move wh2j.zip .\FIGHTERVS\
move whp.zip .\FIGHTERVS\
move xmcota.zip .\FIGHTERVS\
move xmcotaa.zip .\FIGHTERVS\
move xmcotah.zip .\FIGHTERVS\
move xmcotaj1.zip .\FIGHTERVS\
move xmcotaj.zip .\FIGHTERVS\
move xmcotajr.zip .\FIGHTERVS\
move xmcotau.zip .\FIGHTERVS\
move xmvsf.zip .\FIGHTERVS\
move xmvsfa.zip .\FIGHTERVS\
move xmvsfb.zip .\FIGHTERVS\
move xmvsfh.zip .\FIGHTERVS\
move xmvsfj.zip .\FIGHTERVS\
move xmvsfjr1.zip .\FIGHTERVS\
move xmvsfjr2.zip .\FIGHTERVS\
move xmvsfu.zip .\FIGHTERVS\
move xmvsfur1.zip .\FIGHTERVS\
move yiear2.zip .\FIGHTERVS\
move yiear.zip .\FIGHTERVS\
move gunmast.zip .\FIGHTERVS\
move avenger2.zip .\FIGHTERVS\
move avengers.zip .\FIGHTERVS\
move buraiken.zip .\FIGHTERVS\
move downtowj.zip .\FIGHTERVS\
move downtown.zip .\FIGHTERVS\
move fightrol.zip .\FIGHTERVS\
move kyros.zip .\FIGHTERVS\
move kyrosj.zip .\FIGHTERVS\
move mightguy.zip .\FIGHTERVS\
move ridefgtj.zip .\FIGHTERVS\
move ridefgtu.zip .\FIGHTERVS\
move ridingf.zip .\FIGHTERVS\
move rjammer.zip .\FIGHTERVS\
move rollace2.zip .\FIGHTERVS\
move rollace.zip .\FIGHTERVS\
move vandyjal.zip .\FIGHTERVS\
move vandyke.zip .\FIGHTERVS\
