md SPORTS
move bangbead.zip .\SPORTS\
move carpolo.zip .\SPORTS\
move flipshot.zip .\SPORTS\
move gsword.zip .\SPORTS\
move guiness.zip .\SPORTS\
move hotsmash.zip .\SPORTS\
move mayhem.zip .\SPORTS\
move mermaid.zip .\SPORTS\
move paddlema.zip .\SPORTS\
move pkunwar.zip .\SPORTS\
move pkunwarj.zip .\SPORTS\
move rollerg.zip .\SPORTS\
move rollergj.zip .\SPORTS\
move spdball.zip .\SPORTS\
move stoneba2.zip .\SPORTS\
move stonebal.zip .\SPORTS\
move strnskil.zip .\SPORTS\
move wjammers.zip .\SPORTS\
move armwrest.zip .\SPORTS\
move 2020bb.zip .\SPORTS\
move 2020bbh.zip .\SPORTS\
move abaseb2.zip .\SPORTS\
move abaseb.zip .\SPORTS\
move basebal2.zip .\SPORTS\
move bottom9.zip .\SPORTS\
move bottom9n.zip .\SPORTS\
move bstars2.zip .\SPORTS\
move bstars.zip .\SPORTS\
move cbasebal.zip .\SPORTS\
move champbas.zip .\SPORTS\
move champbja.zip .\SPORTS\
move curvebal.zip .\SPORTS\
move dblplay.zip .\SPORTS\
move dleague.zip .\SPORTS\
move dokaben.zip .\SPORTS\
move dplay.zip .\SPORTS\
move ebases.zip .\SPORTS\
move einnings.zip .\SPORTS\
move flyball.zip .\SPORTS\
move gslgr94u.zip .\SPORTS\
move homerun.zip .\SPORTS\
move jitsupro.zip .\SPORTS\
move koshien.zip .\SPORTS\
move kouyakyu.zip .\SPORTS\
move kyukaidk.zip .\SPORTS\
move kyukaido.zip .\SPORTS\
move mstadium.zip .\SPORTS\
move mt_tlbba.zip .\SPORTS\
move pc_bball.zip .\SPORTS\
move pc_bstar.zip .\SPORTS\
move rbibb.zip .\SPORTS\
move rbibba.zip .\SPORTS\
move relief2.zip .\SPORTS\
move relief.zip .\SPORTS\
move sbasebal.zip .\SPORTS\
move stadhero.zip .\SPORTS\
move strkzone.zip .\SPORTS\
move sws92.zip .\SPORTS\
move sws92g.zip .\SPORTS\
move sws93.zip .\SPORTS\
move sws95.zip .\SPORTS\
move sws96.zip .\SPORTS\
move sws97.zip .\SPORTS\
move tornbase.zip .\SPORTS\
move vsbbalja.zip .\SPORTS\
move vsbball.zip .\SPORTS\
move vsbballj.zip .\SPORTS\
move ws89.zip .\SPORTS\
move ws90.zip .\SPORTS\
move ws.zip .\SPORTS\
move wseries.zip .\SPORTS\
move archriv2.zip .\SPORTS\
move archrivl.zip .\SPORTS\
move bsktball.zip .\SPORTS\
move ddream95.zip .\SPORTS\
move ddribble.zip .\SPORTS\
move dunkmnia.zip .\SPORTS\
move harddunj.zip .\SPORTS\
move harddunk.zip .\SPORTS\
move hoops96.zip .\SPORTS\
move inyourfa.zip .\SPORTS\
move jumpshot.zip .\SPORTS\
move nbahangt.zip .\SPORTS\
move nbajam.zip .\SPORTS\
move nbajamr2.zip .\SPORTS\
move nbajamt1.zip .\SPORTS\
move nbajamt2.zip .\SPORTS\
move nbajamt3.zip .\SPORTS\
move nbajamte.zip .\SPORTS\
move nbamaxht.zip .\SPORTS\
move pc_dbldr.zip .\SPORTS\
move punkshot.zip .\SPORTS\
move punksht2.zip .\SPORTS\
move punkshtj.zip .\SPORTS\
move rimrck12.zip .\SPORTS\
move rimrck16.zip .\SPORTS\
move rimrck20.zip .\SPORTS\
move rimrockn.zip .\SPORTS\
move rungun.zip .\SPORTS\
move rungunu.zip .\SPORTS\
move sbasketb.zip .\SPORTS\
move sbasketo.zip .\SPORTS\
move sbasketu.zip .\SPORTS\
move slmdunkj.zip .\SPORTS\
move strhoop.zip .\SPORTS\
move suprslam.zip .\SPORTS\
move alleymas.zip .\SPORTS\
move bowler.zip .\SPORTS\
move bowlrama.zip .\SPORTS\
move capbowl2.zip .\SPORTS\
move capbowl.zip .\SPORTS\
move clbowl.zip .\SPORTS\
move cprobowl.zip .\SPORTS\
move krzybowl.zip .\SPORTS\
move lbowling.zip .\SPORTS\
move medlanes.zip .\SPORTS\
move robotbwl.zip .\SPORTS\
move sbowling.zip .\SPORTS\
move stratab1.zip .\SPORTS\
move stratab.zip .\SPORTS\
move vbowl.zip .\SPORTS\
move vbowlj.zip .\SPORTS\
move wcbowl.zip .\SPORTS\
move wcbwl12.zip .\SPORTS\
move wcbwl161.zip .\SPORTS\
move wcbwl165.zip .\SPORTS\
move ashnojoe.zip .\SPORTS\
move bbbxing.zip .\SPORTS\
move chboxing.zip .\SPORTS\
move finalb.zip .\SPORTS\
move finalbj.zip .\SPORTS\
move fround.zip .\SPORTS\
move froundl.zip .\SPORTS\
move hpuncher.zip .\SPORTS\
move hwchamp.zip .\SPORTS\
move kingofb.zip .\SPORTS\
move pc_miket.zip .\SPORTS\
move poundfor.zip .\SPORTS\
move poundfou.zip .\SPORTS\
move prmtmfgo.zip .\SPORTS\
move prmtmfgt.zip .\SPORTS\
move punchout.zip .\SPORTS\
move ringfgt2.zip .\SPORTS\
move ringfgt.zip .\SPORTS\
move ringkin2.zip .\SPORTS\
move ringkin3.zip .\SPORTS\
move ringking.zip .\SPORTS\
move spnchotj.zip .\SPORTS\
move spnchout.zip .\SPORTS\
move tkoboxng.zip .\SPORTS\
move trstar.zip .\SPORTS\
move trstarj.zip .\SPORTS\
move trstaro.zip .\SPORTS\
move trstaroj.zip .\SPORTS\
move vsgongf.zip .\SPORTS\
move bullfgt.zip .\SPORTS\
move thetogyu.zip .\SPORTS\
move shootbul.zip .\SPORTS\
move nkdodgeb.zip .\SPORTS\
move sdodgeb.zip .\SPORTS\
move spdodgeb.zip .\SPORTS\
move aafb.zip .\SPORTS\
move aafbb.zip .\SPORTS\
move aafbc.zip .\SPORTS\
move aafbd2p.zip .\SPORTS\
move atarifb1.zip .\SPORTS\
move atarifb4.zip .\SPORTS\
move atarifb.zip .\SPORTS\
move blitz2k.zip .\SPORTS\
move blitz99.zip .\SPORTS\
move blitz.zip .\SPORTS\
move cyberb21.zip .\SPORTS\
move cyberb22.zip .\SPORTS\
move cyberb23.zip .\SPORTS\
move cyberb2p.zip .\SPORTS\
move cyberba2.zip .\SPORTS\
move cyberbal.zip .\SPORTS\
move cyberbap.zip .\SPORTS\
move cyberbt1.zip .\SPORTS\
move cyberbt.zip .\SPORTS\
move fbfrenzy.zip .\SPORTS\
move gridiron.zip .\SPORTS\
move hardyard.zip .\SPORTS\
move hardyd10.zip .\SPORTS\
move hiimpact.zip .\SPORTS\
move pc_tbowl.zip .\SPORTS\
move quarterb.zip .\SPORTS\
move quartrba.zip .\SPORTS\
move sfootbal.zip .\SPORTS\
move tbowl.zip .\SPORTS\
move tbowlj.zip .\SPORTS\
move tdfever2.zip .\SPORTS\
move tdfever.zip .\SPORTS\
move tdfeverj.zip .\SPORTS\
move teamqb2.zip .\SPORTS\
move teamqb.zip .\SPORTS\
move vsyard2.zip .\SPORTS\
move vsyard.zip .\SPORTS\
move yard.zip .\SPORTS\
move cscrtry2.zip .\SPORTS\
move cscrtry.zip .\SPORTS\
move pigskin.zip .\SPORTS\
move bigevglf.zip .\SPORTS\
move birdtry.zip .\SPORTS\
move bking2.zip .\SPORTS\
move bking3.zip .\SPORTS\
move bking.zip .\SPORTS\
move countryc.zip .\SPORTS\
move cprogolf.zip .\SPORTS\
move crgolf.zip .\SPORTS\
move crgolfa.zip .\SPORTS\
move crgolfb.zip .\SPORTS\
move crgolfc.zip .\SPORTS\
move dcclub.zip .\SPORTS\
move eaglshot.zip .\SPORTS\
move eaglshta.zip .\SPORTS\
move fitegol2.zip .\SPORTS\
move fitegolf.zip .\SPORTS\
move ggreats2.zip .\SPORTS\
move glfgreat.zip .\SPORTS\
move glfgretj.zip .\SPORTS\
move gtg2.zip .\SPORTS\
move gtg2j.zip .\SPORTS\
move gtg2t.zip .\SPORTS\
move gtg.zip .\SPORTS\
move ladygolf.zip .\SPORTS\
move majtitl2.zip .\SPORTS\
move majtitle.zip .\SPORTS\
move minigol2.zip .\SPORTS\
move minigolf.zip .\SPORTS\
move mt_tgolf.zip .\SPORTS\
move pc_golf.zip .\SPORTS\
move pc_moglf.zip .\SPORTS\
move skingam2.zip .\SPORTS\
move skingame.zip .\SPORTS\
move smgolf.zip .\SPORTS\
move smgolfj.zip .\SPORTS\
move teedoff.zip .\SPORTS\
move tpgolf.zip .\SPORTS\
move turfmast.zip .\SPORTS\
move usclssic.zip .\SPORTS\
move hvysmsh.zip .\SPORTS\
move hvysmsha.zip .\SPORTS\
move hvysmshj.zip .\SPORTS\
move fastfred.zip .\SPORTS\
move flyboyb.zip .\SPORTS\
move propcycl.zip .\SPORTS\
move bladestl.zip .\SPORTS\
move bladstle.zip .\SPORTS\
move bullfgtr.zip .\SPORTS\
move cfghtice.zip .\SPORTS\
move faceoff.zip .\SPORTS\
move hattrick.zip .\SPORTS\
move hitice.zip .\SPORTS\
move hoccer2.zip .\SPORTS\
move hoccer.zip .\SPORTS\
move openice.zip .\SPORTS\
move slapshot.zip .\SPORTS\
move wg3dh.zip .\SPORTS\
move arlingtn.zip .\SPORTS\
move glprac2j.zip .\SPORTS\
move neckneck.zip .\SPORTS\
move stakwin2.zip .\SPORTS\
move stakwin.zip .\SPORTS\
move wwjgtin.zip .\SPORTS\
move horshoes.zip .\SPORTS\
move shuuz2.zip .\SPORTS\
move shuuz.zip .\SPORTS\
move dotron.zip .\SPORTS\
move dotrona.zip .\SPORTS\
move dotrone.zip .\SPORTS\
move csclub.zip .\SPORTS\
move cscluba.zip .\SPORTS\
move csclubh.zip .\SPORTS\
move csclubj.zip .\SPORTS\
move 8ball1.zip .\SPORTS\
move 8ball.zip .\SPORTS\
move 8ballact.zip .\SPORTS\
move 8ballat2.zip .\SPORTS\
move 8bpm.zip .\SPORTS\
move 9ballsh2.zip .\SPORTS\
move 9ballsh3.zip .\SPORTS\
move 9ballsht.zip .\SPORTS\
move billiard.zip .\SPORTS\
move gimeabrk.zip .\SPORTS\
move hustler.zip .\SPORTS\
move hustlerb.zip .\SPORTS\
move pbillian.zip .\SPORTS\
move pbillrd.zip .\SPORTS\
move pbillrds.zip .\SPORTS\
move poolshrk.zip .\SPORTS\
move rackemup.zip .\SPORTS\
move sidepckt.zip .\SPORTS\
move sidepctb.zip .\SPORTS\
move sidepctj.zip .\SPORTS\
move sliksh17.zip .\SPORTS\
move slikshot.zip .\SPORTS\
move spool3.zip .\SPORTS\
move spool3i.zip .\SPORTS\
move thehustj.zip .\SPORTS\
move thehustl.zip .\SPORTS\
move tripool.zip .\SPORTS\
move tripoola.zip .\SPORTS\
move vpool.zip .\SPORTS\
move shuffle.zip .\SPORTS\
move shufshot.zip .\SPORTS\
move sshot137.zip .\SPORTS\
move 720.zip .\SPORTS\
move 720g.zip .\SPORTS\
move 720gr1.zip .\SPORTS\
move 720r1.zip .\SPORTS\
move 720r2.zip .\SPORTS\
move 720r3.zip .\SPORTS\
move alpine.zip .\SPORTS\
move alpinea.zip .\SPORTS\
move dynamski.zip .\SPORTS\
move extdwnhl.zip .\SPORTS\
move pturn.zip .\SPORTS\
move silvland.zip .\SPORTS\
move snowbalt.zip .\SPORTS\
move snowboar.zip .\SPORTS\
move troangel.zip .\SPORTS\
move vsslalom.zip .\SPORTS\
move waterski.zip .\SPORTS\
move winterht.zip .\SPORTS\
move ripcord.zip .\SPORTS\
move skydiver.zip .\SPORTS\
move bigstrik.zip .\SPORTS\
move bigstrkb.zip .\SPORTS\
move bssoccer.zip .\SPORTS\
move cprosocc.zip .\SPORTS\
move cupfinal.zip .\SPORTS\
move dribling.zip .\SPORTS\
move driblino.zip .\SPORTS\
move dsccr94j.zip .\SPORTS\
move dsoccr94.zip .\SPORTS\
move euroch92.zip .\SPORTS\
move exctscc2.zip .\SPORTS\
move exctscca.zip .\SPORTS\
move exctsccb.zip .\SPORTS\
move exctsccr.zip .\SPORTS\
move footchmp.zip .\SPORTS\
move ftsoccer.zip .\SPORTS\
move goal92.zip .\SPORTS\
move goalx3.zip .\SPORTS\
move gstrik2.zip .\SPORTS\
move gstriker.zip .\SPORTS\
move hthero93.zip .\SPORTS\
move hthero95.zip .\SPORTS\
move hthero.zip .\SPORTS\
move hthro95u.zip .\SPORTS\
move idsoccer.zip .\SPORTS\
move intcup94.zip .\SPORTS\
move kickgoal.zip .\SPORTS\
move kicknrun.zip .\SPORTS\
move kickoff.zip .\SPORTS\
move kyustrkr.zip .\SPORTS\
move mexico86.zip .\SPORTS\
move mt_wcsoc.zip .\SPORTS\
move neocup98.zip .\SPORTS\
move pc_wcup.zip .\SPORTS\
move pgoal.zip .\SPORTS\
move powrplay.zip .\SPORTS\
move primglex.zip .\SPORTS\
move prmrsocj.zip .\SPORTS\
move prmrsocr.zip .\SPORTS\
move pwrgoal.zip .\SPORTS\
move scfinals.zip .\SPORTS\
move socbrawl.zip .\SPORTS\
move soccer.zip .\SPORTS\
move ssideki2.zip .\SPORTS\
move ssideki3.zip .\SPORTS\
move ssideki4.zip .\SPORTS\
move ssideki.zip .\SPORTS\
move svf.zip .\SPORTS\
move svs.zip .\SPORTS\
move tehkanwc.zip .\SPORTS\
move tws96.zip .\SPORTS\
move vshoot.zip .\SPORTS\
move vssoccer.zip .\SPORTS\
move wc90.zip .\SPORTS\
move wc90a.zip .\SPORTS\
move wc90b.zip .\SPORTS\
move wc90t.zip .\SPORTS\
move wsf.zip .\SPORTS\
move ssozumo.zip .\SPORTS\
move swimmer.zip .\SPORTS\
move swimmera.zip .\SPORTS\
move swimmerb.zip .\SPORTS\
move toobin1.zip .\SPORTS\
move toobin2.zip .\SPORTS\
move toobin2e.zip .\SPORTS\
move toobin.zip .\SPORTS\
move toobine.zip .\SPORTS\
move toobing.zip .\SPORTS\
move 40love.zip .\SPORTS\
move cptennis.zip .\SPORTS\
move gghost.zip .\SPORTS\
move hstenn10.zip .\SPORTS\
move hstennis.zip .\SPORTS\
move nss_aten.zip .\SPORTS\
move otwalls.zip .\SPORTS\
move passht4b.zip .\SPORTS\
move passshtb.zip .\SPORTS\
move pc_tenis.zip .\SPORTS\
move pingpong.zip .\SPORTS\
move sdtennis.zip .\SPORTS\
move speedspn.zip .\SPORTS\
move squash.zip .\SPORTS\
move sslam.zip .\SPORTS\
move sundance.zip .\SPORTS\
move swcourt.zip .\SPORTS\
move ultennis.zip .\SPORTS\
move vstennis.zip .\SPORTS\
move wldcourt.zip .\SPORTS\
move wtennis.zip .\SPORTS\
move 88games.zip .\SPORTS\
move bootcamp.zip .\SPORTS\
move combasc.zip .\SPORTS\
move combascb.zip .\SPORTS\
move combascj.zip .\SPORTS\
move combasct.zip .\SPORTS\
move esckids.zip .\SPORTS\
move esckidsj.zip .\SPORTS\
move fieldday.zip .\SPORTS\
move goldmedb.zip .\SPORTS\
move goldmedl.zip .\SPORTS\
move herbiedk.zip .\SPORTS\
move hpolym84.zip .\SPORTS\
move hyperspt.zip .\SPORTS\
move hyprolyb.zip .\SPORTS\
move hyprolym.zip .\SPORTS\
move hypsptsp.zip .\SPORTS\
move konami88.zip .\SPORTS\
move machbrkr.zip .\SPORTS\
move mysticm.zip .\SPORTS\
move numanath.zip .\SPORTS\
move numanatj.zip .\SPORTS\
move pc_tkfld.zip .\SPORTS\
move recordbr.zip .\SPORTS\
move trackflc.zip .\SPORTS\
move trackfld.zip .\SPORTS\
move undoukai.zip .\SPORTS\
move wmatch.zip .\SPORTS\
move aceattac.zip .\SPORTS\
move pc_vball.zip .\SPORTS\
move pspikes2.zip .\SPORTS\
move pspikes.zip .\SPORTS\
move pspikesk.zip .\SPORTS\
move spiker.zip .\SPORTS\
move svolley.zip .\SPORTS\
move svolleyk.zip .\SPORTS\
move svolleyu.zip .\SPORTS\
move svolly91.zip .\SPORTS\
move vball2pj.zip .\SPORTS\
move vball.zip .\SPORTS\
move wbeachvl.zip .\SPORTS\
move wcvol95.zip .\SPORTS\
move wcvol95x.zip .\SPORTS\
move 3countb.zip .\SPORTS\
move appoooh.zip .\SPORTS\
move bigprowr.zip .\SPORTS\
move blzntrnd.zip .\SPORTS\
move bodyslam.zip .\SPORTS\
move champwr.zip .\SPORTS\
move champwrj.zip .\SPORTS\
move champwru.zip .\SPORTS\
move chwrestl.zip .\SPORTS\
move dumpmtmt.zip .\SPORTS\
move excthour.zip .\SPORTS\
move mainev2p.zip .\SPORTS\
move mainevt.zip .\SPORTS\
move mainevto.zip .\SPORTS\
move mainsnk.zip .\SPORTS\
move maniach2.zip .\SPORTS\
move maniach.zip .\SPORTS\
move matmania.zip .\SPORTS\
move mbomberj.zip .\SPORTS\
move mbombrd.zip .\SPORTS\
move mbombrdj.zip .\SPORTS\
move pc_pwrst.zip .\SPORTS\
move ringdest.zip .\SPORTS\
move ringohja.zip .\SPORTS\
move ringrage.zip .\SPORTS\
move ringragj.zip .\SPORTS\
move ringragu.zip .\SPORTS\
move slammast.zip .\SPORTS\
move slammasu.zip .\SPORTS\
move smbomb.zip .\SPORTS\
move smbombr1.zip .\SPORTS\
move tagteam.zip .\SPORTS\
move wrestwar.zip .\SPORTS\
move wwfmania.zip .\SPORTS\
move wwfsstar.zip .\SPORTS\
move wwfwfest.zip .\SPORTS\
move wwfwfsta.zip .\SPORTS\
move wwfwfstj.zip .\SPORTS\
