md BALLnPADDLE
move gnbarich.zip .\BALLnPADDLE\
move packbang.zip .\BALLnPADDLE\
move avalnche.zip .\BALLnPADDLE\
move gypsyjug.zip .\BALLnPADDLE\
move kick.zip .\BALLnPADDLE\
move kicka.zip .\BALLnPADDLE\
move peggle.zip .\BALLnPADDLE\
move pegglet.zip .\BALLnPADDLE\
move playball.zip .\BALLnPADDLE\
move snakjack.zip .\BALLnPADDLE\
move wallst.zip .\BALLnPADDLE\
move arkangc.zip .\BALLnPADDLE\
move arkanoid.zip .\BALLnPADDLE\
move arkatayt.zip .\BALLnPADDLE\
move arkatour.zip .\BALLnPADDLE\
move arkbloc2.zip .\BALLnPADDLE\
move arknid2j.zip .\BALLnPADDLE\
move arknid2u.zip .\BALLnPADDLE\
move arknoid2.zip .\BALLnPADDLE\
move arknoidj.zip .\BALLnPADDLE\
move arknoidu.zip .\BALLnPADDLE\
move arknoiuo.zip .\BALLnPADDLE\
move arkretrn.zip .\BALLnPADDLE\
move balcube.zip .\BALLnPADDLE\
move block.zip .\BALLnPADDLE\
move blocka.zip .\BALLnPADDLE\
move blockbl.zip .\BALLnPADDLE\
move blockcar.zip .\BALLnPADDLE\
move blocken.zip .\BALLnPADDLE\
move blockj.zip .\BALLnPADDLE\
move bombbee.zip .\BALLnPADDLE\
move cannonb.zip .\BALLnPADDLE\
move cgraplop.zip .\BALLnPADDLE\
move circus.zip .\BALLnPADDLE\
move clowns1.zip .\BALLnPADDLE\
move clowns.zip .\BALLnPADDLE\
move cubybop.zip .\BALLnPADDLE\
move cutieq.zip .\BALLnPADDLE\
move geebee.zip .\BALLnPADDLE\
move geebeeg.zip .\BALLnPADDLE\
move ghox.zip .\BALLnPADDLE\
move gigasb.zip .\BALLnPADDLE\
move gigasm2b.zip .\BALLnPADDLE\
move goindol.zip .\BALLnPADDLE\
move goindolj.zip .\BALLnPADDLE\
move goindolu.zip .\BALLnPADDLE\
move homo.zip .\BALLnPADDLE\
move offtwalc.zip .\BALLnPADDLE\
move offtwall.zip .\BALLnPADDLE\
move oigas.zip .\BALLnPADDLE\
move paddle2.zip .\BALLnPADDLE\
move plumppop.zip .\BALLnPADDLE\
move popbounc.zip .\BALLnPADDLE\
move puchicar.zip .\BALLnPADDLE\
move quester.zip .\BALLnPADDLE\
move ridleofp.zip .\BALLnPADDLE\
move sarukani.zip .\BALLnPADDLE\
move sbrkout.zip .\BALLnPADDLE\
move sflush.zip .\BALLnPADDLE\
move thunderl.zip .\BALLnPADDLE\
move vblokbrk.zip .\BALLnPADDLE\
move wallc.zip .\BALLnPADDLE\
move warlords.zip .\BALLnPADDLE\
