md LIGHTGUN
move a51mxr3k.zip .\LIGHTGUN\
move alien3.zip .\LIGHTGUN\
move area51.zip .\LIGHTGUN\
move area51mx.zip .\LIGHTGUN\
move bang.zip .\LIGHTGUN\
move bangj.zip .\LIGHTGUN\
move bbusters.zip .\LIGHTGUN\
move carnevil.zip .\LIGHTGUN\
move catch22.zip .\LIGHTGUN\
move cheyenne.zip .\LIGHTGUN\
move chiller.zip .\LIGHTGUN\
move claypign.zip .\LIGHTGUN\
move combat.zip .\LIGHTGUN\
move cracksht.zip .\LIGHTGUN\
move crossbow.zip .\LIGHTGUN\
move cryptklr.zip .\LIGHTGUN\
move desertgu.zip .\LIGHTGUN\
move duckhunt.zip .\LIGHTGUN\
move eggventr.zip .\LIGHTGUN\
move eggvntdx.zip .\LIGHTGUN\
move gdfs.zip .\LIGHTGUN\
move gollygho.zip .\LIGHTGUN\
move greatgun.zip .\LIGHTGUN\
move gunbulet.zip .\LIGHTGUN\
move gunbustr.zip .\LIGHTGUN\
move hitnmis2.zip .\LIGHTGUN\
move hitnmiss.zip .\LIGHTGUN\
move hogalley.zip .\LIGHTGUN\
move le2.zip .\LIGHTGUN\
move le2u.zip .\LIGHTGUN\
move lethalen.zip .\LIGHTGUN\
move lethalj.zip .\LIGHTGUN\
move maxforce.zip .\LIGHTGUN\
move maxf_102.zip .\LIGHTGUN\
move mechatt.zip .\LIGHTGUN\
move nycaptor.zip .\LIGHTGUN\
move oneshot.zip .\LIGHTGUN\
move opwolf3.zip .\LIGHTGUN\
move opwolf3u.zip .\LIGHTGUN\
move opwolf.zip .\LIGHTGUN\
move opwolfb.zip .\LIGHTGUN\
move othunder.zip .\LIGHTGUN\
move othundu.zip .\LIGHTGUN\
move pc_duckh.zip .\LIGHTGUN\
move pc_hgaly.zip .\LIGHTGUN\
move pc_wgnmn.zip .\LIGHTGUN\
move plctr13b.zip .\LIGHTGUN\
move policeto.zip .\LIGHTGUN\
move policetr.zip .\LIGHTGUN\
move ptblank.zip .\LIGHTGUN\
move revx.zip .\LIGHTGUN\
move sgunner2.zip .\LIGHTGUN\
move sgunner.zip .\LIGHTGUN\
move sgunnr2j.zip .\LIGHTGUN\
move spacegun.zip .\LIGHTGUN\
move sshooter.zip .\LIGHTGUN\
move targeth.zip .\LIGHTGUN\
move term2.zip .\LIGHTGUN\
move term2la1.zip .\LIGHTGUN\
move term2la2.zip .\LIGHTGUN\
move tickee.zip .\LIGHTGUN\
move tshoot.zip .\LIGHTGUN\
move undrfire.zip .\LIGHTGUN\
move undrfirj.zip .\LIGHTGUN\
move undrfiru.zip .\LIGHTGUN\
move vsfdf.zip .\LIGHTGUN\
move whodunit.zip .\LIGHTGUN\
move zeropnt2.zip .\LIGHTGUN\
move zeropnt.zip .\LIGHTGUN\
move zeropnta.zip .\LIGHTGUN\
move zombraid.zip .\LIGHTGUN\
