md PUZZLE
move barrier.zip .\PUZZLE\
move blockhl.zip .\PUZZLE\
move boxyboy.zip .\PUZZLE\
move croquis.zip .\PUZZLE\
move crospang.zip .\PUZZLE\
move cshift.zip .\PUZZLE\
move gutsn.zip .\PUZZLE\
move kittenk.zip .\PUZZLE\
move lemmings.zip .\PUZZLE\
move logicpr2.zip .\PUZZLE\
move logicpro.zip .\PUZZLE\
move lotlot.zip .\PUZZLE\
move mmonkey.zip .\PUZZLE\
move motos.zip .\PUZZLE\
move nyanpani.zip .\PUZZLE\
move phozon.zip .\PUZZLE\
move pipedrm.zip .\PUZZLE\
move pipedrmj.zip .\PUZZLE\
move pushman.zip .\PUZZLE\
move quarth.zip .\PUZZLE\
move soukobdx.zip .\PUZZLE\
move spdcoin.zip .\PUZZLE\
move starswep.zip .\PUZZLE\
move tokkae.zip .\PUZZLE\
move wiseguy.zip .\PUZZLE\
move xorworld.zip .\PUZZLE\
move yamyam.zip .\PUZZLE\
move mrdrillr.zip .\PUZZLE\
move aquarium.zip .\PUZZLE\
move atetckt2.zip .\PUZZLE\
move atetcktl.zip .\PUZZLE\
move atetris.zip .\PUZZLE\
move atetrisa.zip .\PUZZLE\
move atetrisb.zip .\PUZZLE\
move atomicp.zip .\PUZZLE\
move bakubaku.zip .\PUZZLE\
move ballbros.zip .\PUZZLE\
move blckout2.zip .\PUZZLE\
move blckoutj.zip .\PUZZLE\
move blockout.zip .\PUZZLE\
move bloxeedc.zip .\PUZZLE\
move cachat.zip .\PUZZLE\
move cgangpzj.zip .\PUZZLE\
move cgangpzl.zip .\PUZZLE\
move chinatwn.zip .\PUZZLE\
move cleopatr.zip .\PUZZLE\
move colmns97.zip .\PUZZLE\
move columns2.zip .\PUZZLE\
move columns.zip .\PUZZLE\
move columnsj.zip .\PUZZLE\
move drmario.zip .\PUZZLE\
move emeralda.zip .\PUZZLE\
move emerldaa.zip .\PUZZLE\
move eto.zip .\PUZZLE\
move fpointbj.zip .\PUZZLE\
move fpointbl.zip .\PUZZLE\
move gururin.zip .\PUZZLE\
move hanagumi.zip .\PUZZLE\
move hatris.zip .\PUZZLE\
move heberpop.zip .\PUZZLE\
move hexion.zip .\PUZZLE\
move iqblock.zip .\PUZZLE\
move joyjoy.zip .\PUZZLE\
move karianx.zip .\PUZZLE\
move klax2.zip .\PUZZLE\
move klax3.zip .\PUZZLE\
move klax.zip .\PUZZLE\
move klaxd.zip .\PUZZLE\
move klaxj.zip .\PUZZLE\
move klaxp1.zip .\PUZZLE\
move klaxp2.zip .\PUZZLE\
move maniacsp.zip .\PUZZLE\
move maniacsq.zip .\PUZZLE\
move manybloc.zip .\PUZZLE\
move mausuke.zip .\PUZZLE\
move mosaic.zip .\PUZZLE\
move mosaica.zip .\PUZZLE\
move mouja.zip .\PUZZLE\
move mslider.zip .\PUZZLE\
move naname.zip .\PUZZLE\
move news.zip .\PUZZLE\
move ohmygod.zip .\PUZZLE\
move panicbom.zip .\PUZZLE\
move pbancho.zip .\PUZZLE\
move pc_drmro.zip .\PUZZLE\
move pnickj.zip .\PUZZLE\
move pnyaa.zip .\PUZZLE\
move poitto.zip .\PUZZLE\
move potopoto.zip .\PUZZLE\
move puyopuy2.zip .\PUZZLE\
move puyopuya.zip .\PUZZLE\
move puyopuyb.zip .\PUZZLE\
move puyopuyo.zip .\PUZZLE\
move puyosun.zip .\PUZZLE\
move puzldama.zip .\PUZZLE\
move puzzli.zip .\PUZZLE\
move senknow.zip .\PUZZLE\
move soldamj.zip .\PUZZLE\
move sparkz.zip .\PUZZLE\
move spf2t.zip .\PUZZLE\
move spf2xj.zip .\PUZZLE\
move ssonicbr.zip .\PUZZLE\
move stkclmns.zip .\PUZZLE\
move tekipaki.zip .\PUZZLE\
move teplus2j.zip .\PUZZLE\
move tetrisbl.zip .\PUZZLE\
move tetrisp2.zip .\PUZZLE\
move tetrisp.zip .\PUZZLE\
move tetrist.zip .\PUZZLE\
move tgm2.zip .\PUZZLE\
move tgm2p.zip .\PUZZLE\
move tkmmpzdm.zip .\PUZZLE\
move toryumon.zip .\PUZZLE\
move tp2m32.zip .\PUZZLE\
move tubeit.zip .\PUZZLE\
move vstetris.zip .\PUZZLE\
move welltris.zip .\PUZZLE\
move xyonix.zip .\PUZZLE\
move daitorid.zip .\PUZZLE\
move dharma.zip .\PUZZLE\
move dragwld2.zip .\PUZZLE\
move drgnwrld.zip .\PUZZLE\
move drgpunch.zip .\PUZZLE\
move hasamu.zip .\PUZZLE\
move kungfut.zip .\PUZZLE\
move lastfort.zip .\PUZZLE\
move matchit.zip .\PUZZLE\
move plotting.zip .\PUZZLE\
move pururun.zip .\PUZZLE\
move puzlstar.zip .\PUZZLE\
move shangha2.zip .\PUZZLE\
move shangha3.zip .\PUZZLE\
move shanghai.zip .\PUZZLE\
move shanhigw.zip .\PUZZLE\
move shisen.zip .\PUZZLE\
move sichuana.zip .\PUZZLE\
move sprtmtch.zip .\PUZZLE\
move toride2g.zip .\PUZZLE\
move domino.zip .\PUZZLE\
move ejihon.zip .\PUZZLE\
move photoy2k.zip .\PUZZLE\
move liblrabl.zip .\PUZZLE\
move panicstr.zip .\PUZZLE\
move qix2.zip .\PUZZLE\
move qix.zip .\PUZZLE\
move qixa.zip .\PUZZLE\
move qixb.zip .\PUZZLE\
move quantum1.zip .\PUZZLE\
move quantum.zip .\PUZZLE\
move quantump.zip .\PUZZLE\
move sqixbl.zip .\PUZZLE\
move twinqix.zip .\PUZZLE\
move volfied.zip .\PUZZLE\
move volfiedj.zip .\PUZZLE\
move volfiedu.zip .\PUZZLE\
move cottong.zip .\PUZZLE\
move cuebrckj.zip .\PUZZLE\
move cuebrick.zip .\PUZZLE\
move gutangtn.zip .\PUZZLE\
move locomotn.zip .\PUZZLE\
move puzlclub.zip .\PUZZLE\
move qwak.zip .\PUZZLE\
move bangball.zip .\PUZZLE\
move chainrec.zip .\PUZZLE\
move cookbib2.zip .\PUZZLE\
move ghostlop.zip .\PUZZLE\
move htchctch.zip .\PUZZLE\
move landmakr.zip .\PUZZLE\
move landmkrp.zip .\PUZZLE\
move magdrop2.zip .\PUZZLE\
move magdrop3.zip .\PUZZLE\
move magdrop.zip .\PUZZLE\
move magdropp.zip .\PUZZLE\
move magicbub.zip .\PUZZLE\
move miexchng.zip .\PUZZLE\
move msgogo.zip .\PUZZLE\
move palamed.zip .\PUZZLE\
move pbobbl2j.zip .\PUZZLE\
move pbobbl2n.zip .\PUZZLE\
move pbobbl2u.zip .\PUZZLE\
move pbobbl2x.zip .\PUZZLE\
move pbobbl3j.zip .\PUZZLE\
move pbobbl3u.zip .\PUZZLE\
move pbobbl4j.zip .\PUZZLE\
move pbobbl4u.zip .\PUZZLE\
move pbobble2.zip .\PUZZLE\
move pbobble3.zip .\PUZZLE\
move pbobble4.zip .\PUZZLE\
move pbobble.zip .\PUZZLE\
move pbobblen.zip .\PUZZLE\
move pbobblna.zip .\PUZZLE\
move popnpop.zip .\PUZZLE\
move popnpopj.zip .\PUZZLE\
move popnpopu.zip .\PUZZLE\
move puzloopj.zip .\PUZZLE\
move puzloopu.zip .\PUZZLE\
move puzzldpr.zip .\PUZZLE\
move puzzledp.zip .\PUZZLE\
move puzzloop.zip .\PUZZLE\
move pzlbowl.zip .\PUZZLE\
move pzloop2j.zip .\PUZZLE\
move rolcrush.zip .\PUZZLE\
move uopoko.zip .\PUZZLE\
move zintrckb.zip .\PUZZLE\
