md DRIVING
move apb1.zip .\DRIVING\
move apb2.zip .\DRIVING\
move apb3.zip .\DRIVING\
move apb4.zip .\DRIVING\
move apb5.zip .\DRIVING\
move apb6.zip .\DRIVING\
move apb.zip .\DRIVING\
move apbf.zip .\DRIVING\
move apbg.zip .\DRIVING\
move bnj.zip .\DRIVING\
move brubber.zip .\DRIVING\
move caractn.zip .\DRIVING\
move carjmbre.zip .\DRIVING\
move cbnj.zip .\DRIVING\
move cburnrb2.zip .\DRIVING\
move cburnrub.zip .\DRIVING\
move demoderb.zip .\DRIVING\
move demoderm.zip .\DRIVING\
move firetrk.zip .\DRIVING\
move joyfulr.zip .\DRIVING\
move kamenrid.zip .\DRIVING\
move mnchmobl.zip .\DRIVING\
move sprint8a.zip .\DRIVING\
move stocker.zip .\DRIVING\
move superbug.zip .\DRIVING\
move turbotag.zip .\DRIVING\
move 280zzzap.zip .\DRIVING\
move harddrb5.zip .\DRIVING\
move harddrb6.zip .\DRIVING\
move harddrc1.zip .\DRIVING\
move harddrcb.zip .\DRIVING\
move harddrcg.zip .\DRIVING\
move harddrg4.zip .\DRIVING\
move harddriv.zip .\DRIVING\
move harddrj6.zip .\DRIVING\
move harddrv2.zip .\DRIVING\
move harddrv3.zip .\DRIVING\
move harddrvb.zip .\DRIVING\
move harddrvc.zip .\DRIVING\
move harddrvg.zip .\DRIVING\
move harddrvj.zip .\DRIVING\
move hdrivair.zip .\DRIVING\
move nitedrvr.zip .\DRIVING\
move racedcb4.zip .\DRIVING\
move racedcg4.zip .\DRIVING\
move racedrb1.zip .\DRIVING\
move racedrb4.zip .\DRIVING\
move racedrc1.zip .\DRIVING\
move racedrc2.zip .\DRIVING\
move racedrc4.zip .\DRIVING\
move racedrcb.zip .\DRIVING\
move racedrcg.zip .\DRIVING\
move racedrg4.zip .\DRIVING\
move racedriv.zip .\DRIVING\
move racedrv3.zip .\DRIVING\
move racedrv4.zip .\DRIVING\
move racedrvb.zip .\DRIVING\
move racedrvc.zip .\DRIVING\
move racedrvg.zip .\DRIVING\
move radm.zip .\DRIVING\
move radr.zip .\DRIVING\
move speedfrk.zip .\DRIVING\
move superchs.zip .\DRIVING\
move bounty.zip .\DRIVING\
move rpatrolb.zip .\DRIVING\
move tugboat.zip .\DRIVING\
move llander1.zip .\DRIVING\
move llander.zip .\DRIVING\
move backfire.zip .\DRIVING\
move blmbycar.zip .\DRIVING\
move blmbycau.zip .\DRIVING\
move chqflag.zip .\DRIVING\
move chqflagj.zip .\DRIVING\
move crshrac2.zip .\DRIVING\
move crshrace.zip .\DRIVING\
move crzrally.zip .\DRIVING\
move dirtfoxj.zip .\DRIVING\
move dragrace.zip .\DRIVING\
move drifto94.zip .\DRIVING\
move driftout.zip .\DRIVING\
move driveout.zip .\DRIVING\
move f1dream.zip .\DRIVING\
move f1dreamb.zip .\DRIVING\
move f1gp2.zip .\DRIVING\
move f1gp.zip .\DRIVING\
move grchamp.zip .\DRIVING\
move gtmr2.zip .\DRIVING\
move gtmr.zip .\DRIVING\
move gtmre.zip .\DRIVING\
move gtmrusa.zip .\DRIVING\
move hotrod.zip .\DRIVING\
move hwrace.zip .\DRIVING\
move lagunar.zip .\DRIVING\
move ledstorm.zip .\DRIVING\
move madgear.zip .\DRIVING\
move madgearj.zip .\DRIVING\
move montecar.zip .\DRIVING\
move neodrift.zip .\DRIVING\
move overtop.zip .\DRIVING\
move pc_rcpam.zip .\DRIVING\
move powerdrv.zip .\DRIVING\
move roadf2.zip .\DRIVING\
move roadf.zip .\DRIVING\
move sformula.zip .\DRIVING\
move splndrbt.zip .\DRIVING\
move sspeedr.zip .\DRIVING\
move ssrj.zip .\DRIVING\
move tail2nos.zip .\DRIVING\
move trally.zip .\DRIVING\
move wrally2.zip .\DRIVING\
move bigrun.zip .\DRIVING\
move buggychl.zip .\DRIVING\
move buggycht.zip .\DRIVING\
move calspeed.zip .\DRIVING\
move chasehq.zip .\DRIVING\
move chasehqj.zip .\DRIVING\
move cischeat.zip .\DRIVING\
move contcirc.zip .\DRIVING\
move contcrcu.zip .\DRIVING\
move crusnu21.zip .\DRIVING\
move crusnu40.zip .\DRIVING\
move crusnusa.zip .\DRIVING\
move crusnw13.zip .\DRIVING\
move crusnw20.zip .\DRIVING\
move crusnwld.zip .\DRIVING\
move dblaxle.zip .\DRIVING\
move drivfrcg.zip .\DRIVING\
move drivfrcp.zip .\DRIVING\
move f1en.zip .\DRIVING\
move f1gpstar.zip .\DRIVING\
move finalap3.zip .\DRIVING\
move finalapc.zip .\DRIVING\
move finalapd.zip .\DRIVING\
move finallap.zip .\DRIVING\
move finalp3a.zip .\DRIVING\
move finlapjb.zip .\DRIVING\
move finlapjc.zip .\DRIVING\
move fourtrax.zip .\DRIVING\
move fullthrl.zip .\DRIVING\
move groundfx.zip .\DRIVING\
move hcrash.zip .\DRIVING\
move hcrashc.zip .\DRIVING\
move hotchase.zip .\DRIVING\
move maxrpm.zip .\DRIVING\
move orunners.zip .\DRIVING\
move outrun.zip .\DRIVING\
move outruna.zip .\DRIVING\
move outrunb.zip .\DRIVING\
move pc_radr2.zip .\DRIVING\
move pc_radrc.zip .\DRIVING\
move polepos1.zip .\DRIVING\
move polepos2.zip .\DRIVING\
move polepos.zip .\DRIVING\
move poleposa.zip .\DRIVING\
move poleps2a.zip .\DRIVING\
move poleps2b.zip .\DRIVING\
move pwheelsj.zip .\DRIVING\
move roadriot.zip .\DRIVING\
move rrreveng.zip .\DRIVING\
move rrrevenp.zip .\DRIVING\
move sfrush.zip .\DRIVING\
move suzuk8h2.zip .\DRIVING\
move suzuk8hj.zip .\DRIVING\
move suzuka8h.zip .\DRIVING\
move topracer.zip .\DRIVING\
move topspedu.zip .\DRIVING\
move topspeed.zip .\DRIVING\
move turbo.zip .\DRIVING\
move turboa.zip .\DRIVING\
move turbob.zip .\DRIVING\
move wecleman.zip .\DRIVING\
move endurob2.zip .\DRIVING\
move endurobl.zip .\DRIVING\
move enduror.zip .\DRIVING\
move hangon.zip .\DRIVING\
move hangonjr.zip .\DRIVING\
move motofren.zip .\DRIVING\
move ridhero.zip .\DRIVING\
move ridheroh.zip .\DRIVING\
move scross.zip .\DRIVING\
move shangon.zip .\DRIVING\
move shangonb.zip .\DRIVING\
move wgp2.zip .\DRIVING\
move wgp.zip .\DRIVING\
move wgpj.zip .\DRIVING\
move wgpjoy.zip .\DRIVING\
move wgpjoya.zip .\DRIVING\
move acedrvrw.zip .\DRIVING\
move konamigt.zip .\DRIVING\
move luckywld.zip .\DRIVING\
move overdriv.zip .\DRIVING\
move rf2.zip .\DRIVING\
move clshroad.zip .\DRIVING\
move excitbkj.zip .\DRIVING\
move excitebk.zip .\DRIVING\
move jcross.zip .\DRIVING\
move kickridr.zip .\DRIVING\
move kikstart.zip .\DRIVING\
move motorace.zip .\DRIVING\
move pc_ebike.zip .\DRIVING\
move rallybik.zip .\DRIVING\
move shtrider.zip .\DRIVING\
move sprcros2.zip .\DRIVING\
move travrusa.zip .\DRIVING\
move amspdwy.zip .\DRIVING\
move amspdwya.zip .\DRIVING\
move badlands.zip .\DRIVING\
move cspring1.zip .\DRIVING\
move csprins1.zip .\DRIVING\
move csprint1.zip .\DRIVING\
move csprint2.zip .\DRIVING\
move csprint.zip .\DRIVING\
move csprintf.zip .\DRIVING\
move csprintg.zip .\DRIVING\
move csprints.zip .\DRIVING\
move grudge.zip .\DRIVING\
move indyheat.zip .\DRIVING\
move offroad.zip .\DRIVING\
move offroadt.zip .\DRIVING\
move pitnrun.zip .\DRIVING\
move redlin2p.zip .\DRIVING\
move sprint1.zip .\DRIVING\
move sprint2.zip .\DRIVING\
move sprint2a.zip .\DRIVING\
move sprint4.zip .\DRIVING\
move sprint4a.zip .\DRIVING\
move sprint8.zip .\DRIVING\
move sspring1.zip .\DRIVING\
move ssprint1.zip .\DRIVING\
move ssprint3.zip .\DRIVING\
move ssprint.zip .\DRIVING\
move ssprintf.zip .\DRIVING\
move ssprintg.zip .\DRIVING\
move ssprints.zip .\DRIVING\
